In [40]:
input_file = '/Users/liuda/Local/data/trading/data/output/trigger/AMZN.csv'


import pandas as pd
ticker_data = pd.read_csv(input_file)
ticker_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Adj Open,Adj High,Adj Low,...,T_T_ShortBullBuy1,T_T_ShortBullBuy2,T_T_LongBullBuy1_0,T_T_LongBullBuy1_1,T_T_LongBullBuy1_2,T_T_LongBullBuy1_3,T_T_LongBullBuy2_0,T_T_LongBullBuy2_1,T_T_LongBullBuy2_2,T_T_LongBullBuy2_3
0,2025-01-02,222.03,225.15,218.19,220.22,220.22,33956600.0,222.03,225.15,218.19,...,0,0,0,0,0,0,0,0,0,0
1,2025-01-03,222.51,225.36,221.62,224.19,224.19,27515606.0,222.51,225.36,221.62,...,0,0,0,0,0,0,0,0,0,0
2,2025-01-04,222.51,225.36,221.62,224.19,224.19,27515606.0,222.51,225.36,221.62,...,0,0,0,0,0,0,0,0,0,0
3,2025-01-05,222.51,225.36,221.62,224.19,224.19,27515606.0,222.51,225.36,221.62,...,0,0,0,0,0,0,0,0,0,0
4,2025-01-06,226.78,228.84,224.84,227.61,227.61,31849831.0,226.78,228.84,224.84,...,0,0,0,0,0,0,0,0,0,0

In [43]:
# key_event_sma_5_cross_sma_20_and_retreat
ticker_data = ticker_data.assign(
	key_event_technical_trend_change=None,
	key_event_institution_op_ratio=0.0,
	key_event_sma_20_retreat=0,
	key_event_sma_5_cross_sma_20_and_retreat=0
)


N = 20
cond1 = (ticker_data['SMA_5_day_Cross_SMA_20_day'] == 1)                  # 当天是上叉
cond2 = ((ticker_data[f'SMA_5_day_Cross_SMA_20_day'] > 0).astype(
int).rolling(window=N, min_periods=1).sum() == 1)  # 近20天内只有一个上叉
cond3 = ((ticker_data[f'SMA_5_day_Cross_SMA_20_day'] < 0).astype(
int).rolling(window=N, min_periods=1).sum() > 0)  # 近20天内有过下叉

ticker_data.loc[cond1 & cond2 & cond3, 'key_event_sma_5_cross_sma_20_and_retreat'] = -1  # 危险信号

cond1 = (ticker_data['SMA_5_day_Cross_SMA_20_day'] == -1)                 # 当天是下叉
cond2 = ((ticker_data[f'SMA_5_day_Cross_SMA_20_day'] < 0).astype(
int).rolling(window=N, min_periods=1).sum() == 1)  # 近20天内只有一个下叉
cond3 = ((ticker_data[f'SMA_5_day_Cross_SMA_20_day'] > 0).astype(
int).rolling(window=N, min_periods=1).sum() > 0)  # 近20天内有过上叉

ticker_data.loc[cond1 & cond2 & cond3, 'key_event_sma_5_cross_sma_20_and_retreat'] = 1    # 买入信号

In [45]:
ticker_data[ticker_data['key_event_sma_5_cross_sma_20_and_retreat'] != 0][['Date', 'SMA_5_day_Cross_SMA_20_day', 'key_event_sma_5_cross_sma_20_and_retreat']]

,Date,SMA_5_day_Cross_SMA_20_day,key_event_sma_5_cross_sma_20_and_retreat
89,2025-04-01,-1.0,1

In [32]:
col_A = 'SMA_5_day'
col_B = 'SMA_20_day'
N = 50

ticker_data[f'{col_A}_Cross_{col_B}_cumsum_{N}'] = (
	(ticker_data[f'{col_A}_Cross_{col_B}'] > 0)
	.astype(int)
	.rolling(window=N, min_periods=1)
	.sum())

# 下叉
ticker_data[f'{col_A}_down_Cross_{col_B}_cumsum_{N}'] = (
	(ticker_data[f'{col_A}_Cross_{col_B}'] < 0)
	.astype(int)
	.rolling(window=N, min_periods=1)
	.sum())

In [33]:
ticker_data = ticker_data.assign(
	key_event_sma_5_cross_sma_20_and_retreat=0,
	key_event_sma_20_retreat=0,
	key_event_sma_5_cross_sma_20_and_retreat_test=0,
)

In [35]:
cond1 = (
    (ticker_data['SMA_5_day_Cross_SMA_20_day'] == 1)                  # 当天是上叉
    & (ticker_data['SMA_5_day_Cross_SMA_20_day_cumsum_50'] == 1)      # 近20天内只是一个上叉
    & (ticker_data['SMA_5_day_down_Cross_SMA_20_day_cumsum_50'] > 0)  # 近20天内有过下叉
)

ticker_data.loc[cond1, 'key_event_sma_5_cross_sma_20_and_retreat'] = -1  # 危险信号

N = 50
cond1 = (ticker_data['SMA_5_day_Cross_SMA_20_day'] == 1)                  # 当天是上叉
cond2 = ((ticker_data[f'SMA_5_day_Cross_SMA_20_day'] > 0).astype(
    int).rolling(window=N, min_periods=1).sum() == 1)  # 近20天内只是一个上叉
cond3 = ((ticker_data[f'SMA_5_day_Cross_SMA_20_day'] < 0).astype(
    int).rolling(window=N, min_periods=1).sum() > 0)  # 近20天内有过下叉


ticker_data.loc[cond1 & cond2 & cond3, 'key_event_sma_5_cross_sma_20_and_retreat_test'] = -1  # 危险信号

In [37]:
pd.set_option('display.max_rows', None)

In [38]:
ticker_data[['Date', "SMA_5_day_Cross_SMA_20_day", 'key_event_sma_5_cross_sma_20_and_retreat', 'key_event_sma_5_cross_sma_20_and_retreat_test']]

,Date,SMA_5_day_Cross_SMA_20_day,key_event_sma_5_cross_sma_20_and_retreat,key_event_sma_5_cross_sma_20_and_retreat_test
0,2025-01-02,0.0,0,0
1,2025-01-03,0.0,0,0
2,2025-01-04,0.0,0,0
3,2025-01-05,0.0,0,0
4,2025-01-06,0.0,0,0
5,2025-01-07,0.0,0,0
6,2025-01-08,0.0,0,0
7,2025-01-09,0.0,0,0
8,2025-01-10,0.0,0,0
9,2025-01-11,0.0,0,0
10,2025-01-12,0.0,0,0
11,2025-01-13,0.0,0,0
12,2025-01-14,0.0,0,0
13,2025-01-15,0.0,0,0
14,2025-01-16,0.0,0,0
15,2025-01-17,0.0,0,0
16,2025-01-18,0.0,0,0
17,2025-01-19,0.0,0,0
18,2025-01-20,0.0,0,0
19,2025-01-21,0.0,0,0
20,2025-01-22,0.0,0,0
21,2025-01-23,0.0,0,0
22,2025-01-24,0.0,0,0
23,2025-01-25,0.0,0,0
24,2025-01-26,0.0,0,0
25,2025-01-27,0.0,0,0
26,2025-01-28,0.0,0,0
27,2025-01-29,0.0,0,0
28,2025-01-30,0.0,0,0
29,2025-01-31,0.0,0,0
30,2025-02-01,0.0,0,0
31,2025-02-02,0.0,0,0
32,2025-02-03,0.0,0,0
33,2025-02-04,0.0,0,0
34,2025-02-05,0.0,0,0
35,2025-02-06,0.0,0,0
36,2025-02-07,0.0,0,0
37,2025-02-08,0.0,0,0
38,2025-02-09,0.0,0,0
39,2025-02-10,0.0,0,0
40,2025-02-11,0.0,0,0
41,2025-02-12,-1.0,0,0
42,2025-02-13,0.0,0,0
43,2025-02-14,0.0,0,0
44,2025-02-15,0.0,0,0
45,2025-02-16,0.0,0,0
46,2025-02-17,0.0,0,0
47,2025-02-18,0.0,0,0
48,2025-02-19,0.0,0,0
49,2025-02-20,0.0,0,0
50,2025-02-21,0.0,0,0
51,2025-02-22,0.0,0,0
52,2025-02-23,0.0,0,0
53,2025-02-24,0.0,0,0
54,2025-02-25,0.0,0,0
55,2025-02-26,0.0,0,0
56,2025-02-27,0.0,0,0
57,2025-02-28,0.0,0,0
58,2025-03-01,0.0,0,0
59,2025-03-02,0.0,0,0
60,2025-03-03,0.0,0,0
61,2025-03-04,0.0,0,0
62,2025-03-05,0.0,0,0
63,2025-03-06,0.0,0,0
64,2025-03-07,0.0,0,0
65,2025-03-08,0.0,0,0
66,2025-03-09,0.0,0,0
67,2025-03-10,0.0,0,0
68,2025-03-11,0.0,0,0
69,2025-03-12,0.0,0,0
70,2025-03-13,0.0,0,0
71,2025-03-14,0.0,0,0
72,2025-03-15,0.0,0,0
73,2025-03-16,0.0,0,0
74,2025-03-17,0.0,0,0
75,2025-03-18,0.0,0,0
76,2025-03-19,0.0,0,0
77,2025-03-20,0.0,0,0
78,2025-03-21,0.0,0,0
79,2025-03-22,0.0,0,0
80,2025-03-23,0.0,0,0
81,2025-03-24,0.0,0,0
82,2025-03-25,0.0,0,0
83,2025-03-26,0.0,0,0
84,2025-03-27,1.0,-1,-1
85,2025-03-28,0.0,0,0
86,2025-03-29,0.0,0,0
87,2025-03-30,0.0,0,0
88,2025-03-31,0.0,0,0
89,2025-04-01,-1.0,0,0
90,2025-04-02,0.0,0,0
91,2025-04-03,0.0,0,0
92,2025-04-04,0.0,0,0
93,2025-04-05,0.0,0,0
94,2025-04-06,0.0,0,0
95,2025-04-07,0.0,0,0
96,2025-04-08,0.0,0,0
97,2025-04-09,0.0,0,0
98,2025-04-10,0.0,0,0
99,2025-04-11,0.0,0,0
100,2025-04-12,0.0,0,0
101,2025-04-13,0.0,0,0
102,2025-04-14,0.0,0,0
103,2025-04-15,0.0,0,0
104,2025-04-16,0.0,0,0
105,2025-04-17,0.0,0,0
106,2025-04-18,0.0,0,0
107,2025-04-19,0.0,0,0
108,2025-04-20,0.0,0,0
109,2025-04-21,0.0,0,0
110,2025-04-22,0.0,0,0
111,2025-04-23,0.0,0,0
112,2025-04-24,0.0,0,0
113,2025-04-25,0.0,0,0
114,2025-04-26,0.0,0,0
115,2025-04-27,0.0,0,0
116,2025-04-28,1.0,0,0
117,2025-04-29,0.0,0,0
118,2025-04-30,0.0,0,0
119,2025-05-01,0.0,0,0
120,2025-05-02,0.0,0,0
121,2025-05-03,0.0,0,0
122,2025-05-04,0.0,0,0
123,2025-05-05,0.0,0,0
124,2025-05-06,0.0,0,0
125,2025-05-07,0.0,0,0
126,2025-05-08,0.0,0,0
127,2025-05-09,0.0,0,0
128,2025-05-10,0.0,0,0
129,2025-05-11,0.0,0,0
130,2025-05-12,0.0,0,0
131,2025-05-13,0.0,0,0
132,2025-05-14,0.0,0,0
133,2025-05-15,0.0,0,0
134,2025-05-16,0.0,0,0
135,2025-05-17,0.0,0,0
136,2025-05-18,0.0,0,0
137,2025-05-19,0.0,0,0
138,2025-05-20,0.0,0,0
139,2025-05-21,0.0,0,0
140,2025-05-22,0.0,0,0
141,2025-05-23,0.0,0,0
142,2025-05-24,0.0,0,0
143,2025-05-25,0.0,0,0
144,2025-05-26,0.0,0,0
145,2025-05-27,0.0,0,0
146,2025-05-28,0.0,0,0
147,2025-05-29,0.0,0,0
148,2025-05-30,0.0,0,0
149,2025-05-31,0.0,0,0
150,2025-06-01,0.0,0,0
151,2025-06-02,0.0,0,0
152,2025-06-03,0.0,0,0
153,2025-06-04,0.0,0,0
154,2025-06-05,0.0,0,0
155,2025-06-06,0.0,0,0
156,2025-06-07,0.0,0,0
157,2025-06-08,0.0,0,0
158,2025-06-09,0.0,0,0
159,2025-06-10,0.0,0,0
160,2025-06-11,0.0,0,0
161,2025-06-12,0.0,0,0
162,2025-06-13,0.0,0,0
163,2025-06-14,0.0,0,0
164,2025-06-15,0.0,0,0
165,2025-06-16,0.0,0,0
166,2025-06-17,0.0,0,0
167,2025-06-18,0.0,0,0
168,2025-06-19,0.0,0,0
169,2025-06-20,0.0,0,0
170,2025-06-21,0.0,0,0
171,2025-06-22,0.0,0,0
172,2025-06-23,0.0,0,0
173,2025-06-24,0.0,0,0
174,2025-06-25,0.0,0,0
175,2025-06-26,0.0,0,0
176,2025-06-27,0.0,0,0
177,2025-06-28,0.0,0,0
178,2025-06-29,0.0,0,0
179,2025-06-30,0.0,0,0
180,2025-07-01,0.0,0,0
181,2025-07-02,0.0,0,0
182,2025-07-03,0.0,0,0
183,2025-07-04,0.0,0,0
184,2025-07-05,0.0,0,0
185,2025-07-06,0.0,0,0
186,2025-07-07,0.0,0,0
187,2025-07-08,0.0,0,0
188,2025-07-09,0.0,0,0
189,2025-07-10,0.0,0,0
190,2025-07-11,0.0,0,0
191,2025-07-12,0.0,0,0
192,2025-07-13,0.0,0,0
193,2025-07-14,0.0,0,0
194,2025-07-15,0.0,0,0
195,2025-07-16,0.0,0,0
196,2025-07-17,0.0,0,0
197,2025-07-18,0.0,0,0
198,2025-07-19,0.0,0,0
199,2025-07-20,0.0,0,0
200,2025-07-21,0.0,0,0
201,2025-07-22,0.0,0,0
202,2025-07-23,0.0,0,0
203,2025-07-24,0.0,0,0
204,2025-07-25,0.0,0,0
205,2025-07-26,0.0,0,0
206,2025-07-27,0.0,0,0
207,2025-07-28,0.0,0,0
208,2025-07-29,0.0,0,0
209,2025-07-30,0.0,0,0
210,2025-07-31,0.0,0,0
211,2025-08-01,0.0,0,0
212,2025-08-02,0.0,0,0
213,2025-08-03,0.0,0,0
214,2025-08-04,-1.0,0,0
215,2025-08-05,0.0,0,0
216,2025-08-06,0.0,0,0

In [39]:

ticker_data[ticker_data['key_event_sma_5_cross_sma_20_and_retreat'] != 0][
	['Date', 'key_event_sma_5_cross_sma_20_and_retreat', 'key_event_sma_5_cross_sma_20_and_retreat_test']]

,Date,key_event_sma_5_cross_sma_20_and_retreat,key_event_sma_5_cross_sma_20_and_retreat_test
84,2025-03-27,-1,-1