In [1]:
import pandas as pd
import numpy as np

In [14]:
import os
import sys
import pandas as pd
import pandas_market_calendars as mcal
from datetime import datetime, date, timedelta

# 获取 NYSE 日历# NYSE 是 New York Stock Exchange（纽约证券交易所） 的缩写
calendar = mcal.get_calendar('NYSE')

def is_trading_date(input_date):
    # 获取今天日期（注意时区）
    today = datetime.today().date()

    # 判断是否为交易日
    schedule = calendar.schedule(start_date=today, end_date=today)
    is_trading_day = not schedule.empty

    return is_trading_day


def is_weekly_last_trading_date(input_date):
    if isinstance(input_date, str):
        input_date = pd.to_datetime(input_date).date()
    elif isinstance(input_date, pd.Timestamp):
        input_date = input_date.date()

    # 找到 input_date 所在的那一周（周一至周日）
    year, week_num, weekday = input_date.isocalendar()

    # 构造这一周的日期范围
    start_of_week = date.fromisocalendar(year, week_num, 1)  # 周一
    end_of_week = date.fromisocalendar(year, week_num, 7)    # 周日

    # 获取这一周内的所有交易日
    schedule = calendar.schedule(start_date=start_of_week, end_date=end_of_week)
    trading_days = schedule.index.date.tolist()

    if not trading_days:
        return False

    last_trading_day_of_week = trading_days[-1]

    return input_date == last_trading_day_of_week


def is_monthly_last_trading_date(input_date):
    if isinstance(input_date, str):
        input_date = pd.to_datetime(input_date).date()
    elif isinstance(input_date, pd.Timestamp):
        input_date = input_date.date()

    # 找到 input_date 所在月份的第一天和最后一天
    first_day_of_month = input_date.replace(day=1)
    next_month = first_day_of_month + timedelta(days=32)
    last_day_of_month = next_month.replace(day=1) - timedelta(days=1)

    # 获取该月的所有交易日
    schedule = calendar.schedule(start_date=first_day_of_month, end_date=last_day_of_month)
    trading_days = schedule.index.date.tolist()

    if not trading_days:
        return False

    last_trading_day_of_month = trading_days[-1]

    return input_date == last_trading_day_of_month

In [19]:
input_date = datetime.today().date() + timedelta(days=2) 
print(input_date)


print(is_monthly_last_trading_date(input_date))
print(is_weekly_last_trading_date(input_date))

2025-05-30
True
True

In [28]:
import yfinance as yf

proxies = {'http': 'http://127.0.0.1:10086', 'https': 'http://127.0.0.1:10086'}

ticker_data = yf.download('QQQ', start='2025-01-01', end='2025-05-29',
				interval='1d', proxy=proxies, auto_adjust=True)
ticker_data

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker             QQQ         QQQ         QQQ         QQQ       QQQ
Date
2025-01-02  509.470245  515.870704  504.956956  513.534162  36389800
2025-01-03  517.807800  518.876214  511.766822  512.585547  29059500
2025-01-06  523.758911  527.133883  521.252700  523.239727  36109700
2025-01-07  514.412842  525.206742  512.515708  524.807374  36690300
2025-01-08  514.502747  516.150253  509.809733  514.313027  30777800
...                ...         ...         ...         ...       ...
2025-05-21  513.039978  523.000000  511.239990  516.270020  71292800
2025-05-22  514.000000  517.710022  512.299988  513.659973  55607200
2025-05-23  509.239990  511.839996  505.579987  506.179993  58368100
2025-05-27  521.219971  521.710022  514.590027  516.150024  47226300
2025-05-28  518.909973  523.679993  518.390015  522.179993  45057800

[100 rows x 5 columns]

In [26]:
ticker_data = yf.download('SPY', start='2025-05-01', end='2025-05-29',
				interval='1d', proxy=proxies, auto_adjust=True)
ticker_data

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker             SPY         SPY         SPY         SPY       SPY
Date
2025-05-01  558.469971  564.070007  557.859985  560.369995  63186100
2025-05-02  566.760010  568.380005  562.380005  564.729980  60717300
2025-05-05  563.510010  566.650024  561.700012  562.570007  38659200
2025-05-06  558.799988  563.349976  556.960022  557.929993  48264700
2025-05-07  561.150024  563.820007  556.039978  560.150024  55588000
2025-05-08  565.059998  570.309998  561.700012  565.239990  65130800
2025-05-09  564.340027  567.500000  562.760010  566.479980  37603400
2025-05-12  582.989990  583.000000  577.039978  581.469971  78993600
2025-05-13  586.840027  589.080017  582.840027  583.409973  67947200
2025-05-14  587.590027  588.979980  585.539978  587.809998  66283500
2025-05-15  590.460022  590.969971  585.099976  585.559998  71268100
2025-05-16  594.200012  594.500000  589.280029  591.250000  76052100
2025-05-19  594.849976  595.539978  588.099976  588.099976  68168500
2025-05-20  592.849976  594.049988  589.599976  593.090027  60614500
2025-05-21  582.859985  592.580017  581.820007  588.440002  95197700
2025-05-22  583.090027  586.619995  581.409973  582.659973  70860400
2025-05-23  579.109985  581.809998  575.599976  575.979980  76029000
2025-05-27  591.150024  591.309998  578.429993  586.070007  72588500
2025-05-28  587.729980  592.770020  586.989990  591.559998  66516700

In [25]:
ticker_data = yf.download('TSLA', start='2025-05-01', end='2025-05-29',
				interval='1d', proxy=proxies, auto_adjust=False)
ticker_data

[*********************100%***********************]  1 of 1 completed

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,TSLA,TSLA,TSLA,TSLA,TSLA,TSLA
Date,,,,,,
2025-05-01,280.519989,280.519989,290.869995,279.809998,280.010010,99659000
2025-05-02,287.209991,287.209991,294.779999,279.809998,284.899994,114454700
2025-05-05,280.260010,280.260010,284.850006,274.399994,284.570007,94618900
2025-05-06,275.350006,275.350006,277.730011,271.350006,273.109985,76715800
2025-05-07,276.220001,276.220001,277.920013,271.000000,276.880005,71592600
2025-05-08,284.820007,284.820007,289.799988,279.410004,279.630005,97539400
2025-05-09,298.260010,298.260010,307.040009,290.000000,290.209991,132387800
2025-05-12,318.380005,318.380005,322.209991,311.500000,321.989990,112826700
2025-05-13,334.070007,334.070007,337.589996,316.799988,320.000000,136992600
2025-05-14,347.679993,347.679993,350.000000,337.000000,342.500000,136997300
2025-05-15,342.820007,342.820007,346.140015,334.720001,340.339996,97882600
2025-05-16,349.980011,349.980011,351.619995,342.329987,346.239990,95895700
2025-05-19,342.089996,342.089996,343.000000,333.369995,336.299988,88869900
2025-05-20,343.820007,343.820007,354.989990,341.630005,347.869995,131715500
2025-05-21,334.619995,334.619995,347.350006,332.200012,344.429993,102354800
2025-05-22,341.040009,341.040009,347.269989,331.390015,331.899994,97113400
2025-05-23,339.339996,339.339996,343.179993,333.209991,337.920013,84654800
2025-05-27,362.890015,362.890015,363.790009,347.320007,347.350006,120146400
2025-05-28,356.899994,356.899994,365.000000,355.910004,364.839996,90186700

In [ ]:
import pandas as pd

In [48]:
current_date = pd.Timestamp.today() - timedelta(hours=14) 
print(current_date)

delta_days = 1 if current_date.hour <= 20 else 0     # UTC时间20点对应NY时间16点
print(delta_days)

previous_business_day = current_date - pd.offsets.BusinessDay(n=delta_days)
previous_business_day = previous_business_day.strftime('%Y-%m-%d')
print(previous_business_day)

2025-05-28 21:03:16.906474
0
2025-05-28

In [57]:
API_KEY = 'BSLRAR2IZ893LHH2'
ticker_id = "TSLA"
interval = "5min"  # 1min, 5min, 15min, 30min, 60min

In [ ]:
"""
This API returns raw (as-traded) daily time series 
- (date, daily open, daily high, daily low, daily close, daily volume) of the global equity specified, 
- covering 20+ years of historical data. 
- The OHLCV data is sometimes called "candles" in finance literature. 
- If you are also interested in split/dividend-adjusted data, please use the Daily Adjusted API, 
- which covers adjusted close values and historical split and dividend events.
"""

https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=TSLA&apikey=BSLRAR2IZ893LHH2&datatype=csv
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=TSLA&apikey=BSLRAR2IZ893LHH2&datatype=csv

https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=TSLA&apikey=BSLRAR2IZ893LHH2&datatype=csv
https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol={ticker_id}&apikey={API_KEY}&datatype=csv

In [65]:
import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=demo'
r = requests.get(url)
data = r.json()
print(data)

{'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume', '2. Symbol': 'IBM', '3. Last Refreshed': '2025-05-29 19:55:00', '4. Interval': '5min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'}, 'Time Series (5min)': {'2025-05-29 19:55:00': {'1. open': '258.6800', '2. high': '258.6800', '3. low': '258.6800', '4. close': '258.6800', '5. volume': '15'}, '2025-05-29 19:45:00': {'1. open': '258.3100', '2. high': '258.3100', '3. low': '258.3100', '4. close': '258.3100', '5. volume': '10'}, '2025-05-29 19:40:00': {'1. open': '258.6900', '2. high': '258.6900', '3. low': '258.6900', '4. close': '258.6900', '5. volume': '10'}, '2025-05-29 19:20:00': {'1. open': '258.8699', '2. high': '258.9900', '3. low': '256.8600', '4. close': '258.9900', '5. volume': '5'}, '2025-05-29 19:05:00': {'1. open': '258.8700', '2. high': '258.8700', '3. low': '258.8700', '4. close': '258.8700', '5. volume': '13'}, '2025-05-29 19:00:00': {'1. open': '258.6900', '2. high': '258.6900', '3. low': '258.6900', '4. close': '258.6900', '5. volume': '430669'}, '2025-05-29 18:55:00': {'1. open': '258.2600', '2. high': '258.3100', '3. low': '258.2600', '4. close': '258.3100', '5. volume': '138'}, '2025-05-29 18:40:00': {'1. open': '258.2500', '2. high': '258.2600', '3. low': '258.2500', '4. close': '258.2600', '5. volume': '25'}, '2025-05-29 18:30:00': {'1. open': '258.6900', '2. high': '258.8700', '3. low': '258.6900', '4. close': '258.8700', '5. volume': '430670'}, '2025-05-29 18:25:00': {'1. open': '258.8700', '2. high': '258.8700', '3. low': '258.8700', '4. close': '258.8700', '5. volume': '1'}, '2025-05-29 18:20:00': {'1. open': '258.5800', '2. high': '258.5800', '3. low': '258.5800', '4. close': '258.5800', '5. volume': '3'}, '2025-05-29 18:15:00': {'1. open': '258.5700', '2. high': '258.5700', '3. low': '258.5700', '4. close': '258.5700', '5. volume': '50'}, '2025-05-29 18:10:00': {'1. open': '258.5800', '2. high': '258.5800', '3. low': '258.2700', '4. close': '258.2700', '5. volume': '2'}, '2025-05-29 18:05:00': {'1. open': '258.8600', '2. high': '258.8600', '3. low': '256.8600', '4. close': '258.5700', '5. volume': '144'}, '2025-05-29 17:55:00': {'1. open': '258.8600', '2. high': '258.8600', '3. low': '258.5800', '4. close': '258.5800', '5. volume': '7'}, '2025-05-29 17:50:00': {'1. open': '258.8600', '2. high': '258.9200', '3. low': '258.8600', '4. close': '258.8600', '5. volume': '4'}, '2025-05-29 17:45:00': {'1. open': '258.0590', '2. high': '258.9900', '3. low': '258.0590', '4. close': '258.9214', '5. volume': '53'}, '2025-05-29 17:30:00': {'1. open': '258.5800', '2. high': '258.8600', '3. low': '258.5800', '4. close': '258.8600', '5. volume': '4'}, '2025-05-29 17:25:00': {'1. open': '258.5700', '2. high': '258.6900', '3. low': '258.5700', '4. close': '258.6900', '5. volume': '2661'}, '2025-05-29 17:20:00': {'1. open': '259.6400', '2. high': '259.8000', '3. low': '258.9800', '4. close': '259.0300', '5. volume': '98'}, '2025-05-29 17:10:00': {'1. open': '259.8000', '2. high': '259.8000', '3. low': '259.8000', '4. close': '259.8000', '5. volume': '2'}, '2025-05-29 17:05:00': {'1. open': '258.5700', '2. high': '258.5700', '3. low': '258.5700', '4. close': '258.5700', '5. volume': '25'}, '2025-05-29 16:55:00': {'1. open': '259.1700', '2. high': '259.1700', '3. low': '259.0000', '4. close': '259.0000', '5. volume': '26'}, '2025-05-29 16:50:00': {'1. open': '259.0400', '2. high': '259.0500', '3. low': '259.0000', '4. close': '259.0400', '5. volume': '18'}, '2025-05-29 16:45:00': {'1. open': '259.9118', '2. high': '259.9118', '3. low': '257.2000', '4. close': '259.0000', '5. volume': '216'}, '2025-05-29 16:40:00': {'1. open': '257.0000', '2. high': '259.8000', '3. low': '257.0000', '4. close': '258.5800', '5. volume': '127'}, '2025-05-29 16:35:00': {'1. open': '258.6900', '2. high': '258.6900', '3. low': '258.6900', '4. close': '258.6900', '5. volume': '300'}, '2025-05-29 16:25:00': {'1. open': '258.6900', '2. high': '258.6900', '3. low': '258.6900', '4. close': '258.6900', '5. volume': '5250'}, '2025-05-29 16:20:00': {'1. open': '258.6900', '2. high': '258.6900', '3. low': '258.6900', '4. close': '258.6900', '5. volume': '6195'}, '2025-05-29 16:15:00': {'1. open': '258.6900', '2. high': '259.8000', '3. low': '257.0000', '4. close': '258.7800', '5. volume': '256'}, '2025-05-29 16:10:00': {'1. open': '258.6900', '2. high': '259.9125', '3. low': '258.6900', '4. close': '259.3500', '5. volume': '430672'}, '2025-05-29 16:05:00': {'1. open': '258.6900', '2. high': '259.3900', '3. low': '258.6900', '4. close': '258.6900', '5. volume': '2913'}, '2025-05-29 16:00:00': {'1. open': '258.6900', '2. high': '258.6900', '3. low': '258.6900', '4. close': '258.6900', '5. volume': '926696'}, '2025-05-29 15:55:00': {'1. open': '258.6000', '2. high': '258.8700', '3. low': '258.4900', '4. close': '258.6900', '5. volume': '180283'}, '2025-05-29 15:50:00': {'1. open': '259.2600', '2. high': '259.4100', '3. low': '258.4600', '4. close': '258.5650', '5. volume': '59947'}, '2025-05-29 15:45:00': {'1. open': '258.8200', '2. high': '259.3800', '3. low': '258.7700', '4. close': '259.1800', '5. volume': '48724'}, '2025-05-29 15:40:00': {'1. open': '258.6800', '2. high': '258.8700', '3. low': '258.6700', '4. close': '258.7700', '5. volume': '24637'}, '2025-05-29 15:35:00': {'1. open': '258.7200', '2. high': '258.7500', '3. low': '258.5405', '4. close': '258.6400', '5. volume': '29696'}, '2025-05-29 15:30:00': {'1. open': '258.6300', '2. high': '258.8200', '3. low': '258.6300', '4. close': '258.7475', '5. volume': '33538'}, '2025-05-29 15:25:00': {'1. open': '258.9024', '2. high': '258.9800', '3. low': '258.6200', '4. close': '258.6500', '5. volume': '15929'}, '2025-05-29 15:20:00': {'1. open': '258.6524', '2. high': '258.9200', '3. low': '258.6524', '4. close': '258.8650', '5. volume': '40330'}, '2025-05-29 15:15:00': {'1. open': '258.4600', '2. high': '258.6850', '3. low': '258.3600', '4. close': '258.6850', '5. volume': '20048'}, '2025-05-29 15:10:00': {'1. open': '258.6550', '2. high': '258.7450', '3. low': '258.4500', '4. close': '258.4500', '5. volume': '19673'}, '2025-05-29 15:05:00': {'1. open': '258.8300', '2. high': '258.8500', '3. low': '258.5300', '4. close': '258.6661', '5. volume': '26308'}, '2025-05-29 15:00:00': {'1. open': '258.7200', '2. high': '258.9203', '3. low': '258.7200', '4. close': '258.8950', '5. volume': '10349'}, '2025-05-29 14:55:00': {'1. open': '258.9600', '2. high': '259.0200', '3. low': '258.5600', '4. close': '258.7250', '5. volume': '16031'}, '2025-05-29 14:50:00': {'1. open': '259.0250', '2. high': '259.0800', '3. low': '258.9700', '4. close': '258.9800', '5. volume': '12801'}, '2025-05-29 14:45:00': {'1. open': '259.1350', '2. high': '259.1350', '3. low': '258.9900', '4. close': '259.0100', '5. volume': '10320'}, '2025-05-29 14:40:00': {'1. open': '259.0600', '2. high': '259.2200', '3. low': '259.0200', '4. close': '259.0900', '5. volume': '10843'}, '2025-05-29 14:35:00': {'1. open': '258.9400', '2. high': '259.0700', '3. low': '258.9200', '4. close': '259.0650', '5. volume': '13151'}, '2025-05-29 14:30:00': {'1. open': '258.7300', '2. high': '258.9750', '3. low': '258.7100', '4. close': '258.9250', '5. volume': '10989'}, '2025-05-29 14:25:00': {'1. open': '258.8600', '2. high': '258.9600', '3. low': '258.6050', '4. close': '258.7300', '5. volume': '14810'}, '2025-05-29 14:20:00': {'1. open': '258.7400', '2. high': '259.0300', '3. low': '258.5601', '4. close': '258.8100', '5. volume': '15527'}, '2025-05-29 14:15:00': {'1. open': '259.2600', '2. high': '259.2600', '3. low': '258.7300', '4. close': '258.7950', '5. volume': '18432'}, '2025-05-29 14:10:00': {'1. open': '259.1400', '2. high': '259.2900', '3. low': '259.0600', '4. close': '259.2200', '5. volume': '10900'}, '2025-05-29 14:05:00': {'1. open': '259.2500', '2. high': '259.3150', '3. low': '259.0900', '4. close': '259.0900', '5. volume': '11415'}, '2025-05-29 14:00:00': {'1. open': '259.0650', '2. high': '259.2700', '3. low': '259.0200', '4. close': '259.1750', '5. volume': '15187'}, '2025-05-29 13:55:00': {'1. open': '259.3000', '2. high': '259.3800', '3. low': '259.0300', '4. close': '259.1148', '5. volume': '15554'}, '2025-05-29 13:50:00': {'1. open': '259.1200', '2. high': '259.3700', '3. low': '259.0185', '4. close': '259.3000', '5. volume': '17520'}, '2025-05-29 13:45:00': {'1. open': '258.9500', '2. high': '259.0800', '3. low': '258.8400', '4. close': '259.0450', '5. volume': '30397'}, '2025-05-29 13:40:00': {'1. open': '258.8700', '2. high': '259.0800', '3. low': '258.8650', '4. close': '258.9250', '5. volume': '12346'}, '2025-05-29 13:35:00': {'1. open': '258.7000', '2. high': '258.9000', '3. low': '258.6800', '4. close': '258.9000', '5. volume': '11166'}, '2025-05-29 13:30:00': {'1. open': '258.7500', '2. high': '258.9800', '3. low': '258.6800', '4. close': '258.6800', '5. volume': '11383'}, '2025-05-29 13:25:00': {'1. open': '258.7650', '2. high': '258.8300', '3. low': '258.5850', '4. close': '258.7200', '5. volume': '10848'}, '2025-05-29 13:20:00': {'1. open': '258.6950', '2. high': '258.9050', '3. low': '258.6000', '4. close': '258.7650', '5. volume': '8380'}, '2025-05-29 13:15:00': {'1. open': '258.8700', '2. high': '258.8700', '3. low': '258.5300', '4. close': '258.5600', '5. volume': '9621'}, '2025-05-29 13:10:00': {'1. open': '258.6300', '2. high': '258.9099', '3. low': '258.6300', '4. close': '258.8600', '5. volume': '12667'}, '2025-05-29 13:05:00': {'1. open': '258.9000', '2. high': '258.9700', '3. low': '258.5800', '4. close': '258.7300', '5. volume': '11725'}, '2025-05-29 13:00:00': {'1. open': '258.7800', '2. high': '259.0800', '3. low': '258.7800', '4. close': '258.9500', '5. volume': '14941'}, '2025-05-29 12:55:00': {'1. open': '258.7100', '2. high': '258.9700', '3. low': '258.5200', '4. close': '258.8750', '5. volume': '14303'}, '2025-05-29 12:50:00': {'1. open': '258.4750', '2. high': '258.7200', '3. low': '258.4500', '4. close': '258.7200', '5. volume': '11229'}, '2025-05-29 12:45:00': {'1. open': '258.6100', '2. high': '258.6700', '3. low': '258.4000', '4. close': '258.4000', '5. volume': '17167'}, '2025-05-29 12:40:00': {'1. open': '258.5700', '2. high': '258.8200', '3. low': '258.5200', '4. close': '258.6000', '5. volume': '15451'}, '2025-05-29 12:35:00': {'1. open': '258.4800', '2. high': '258.6100', '3. low': '258.4000', '4. close': '258.4850', '5. volume': '23516'}, '2025-05-29 12:30:00': {'1. open': '258.3752', '2. high': '258.5600', '3. low': '258.2500', '4. close': '258.4800', '5. volume': '26235'}, '2025-05-29 12:25:00': {'1. open': '258.1800', '2. high': '258.3450', '3. low': '258.1100', '4. close': '258.3100', '5. volume': '12379'}, '2025-05-29 12:20:00': {'1. open': '258.1558', '2. high': '258.2550', '3. low': '257.9500', '4. close': '258.2550', '5. volume': '30779'}, '2025-05-29 12:15:00': {'1. open': '257.6400', '2. high': '258.1200', '3. low': '257.6400', '4. close': '258.1200', '5. volume': '11480'}, '2025-05-29 12:10:00': {'1. open': '257.2200', '2. high': '257.6800', '3. low': '257.2200', '4. close': '257.5900', '5. volume': '20210'}, '2025-05-29 12:05:00': {'1. open': '257.2250', '2. high': '257.2800', '3. low': '257.1200', '4. close': '257.2250', '5. volume': '17868'}, '2025-05-29 12:00:00': {'1. open': '257.1300', '2. high': '257.3557', '3. low': '256.7700', '4. close': '257.2850', '5. volume': '19721'}, '2025-05-29 11:55:00': {'1. open': '258.0861', '2. high': '258.0861', '3. low': '256.9184', '4. close': '257.1350', '5. volume': '28456'}, '2025-05-29 11:50:00': {'1. open': '257.9000', '2. high': '258.1687', '3. low': '257.8850', '4. close': '257.9600', '5. volume': '19793'}, '2025-05-29 11:45:00': {'1. open': '257.9100', '2. high': '258.0540', '3. low': '257.7900', '4. close': '257.8500', '5. volume': '14857'}, '2025-05-29 11:40:00': {'1. open': '257.9100', '2. high': '258.1500', '3. low': '257.8701', '4. close': '257.9550', '5. volume': '17401'}, '2025-05-29 11:35:00': {'1. open': '258.0800', '2. high': '258.2700', '3. low': '257.9100', '4. close': '257.9900', '5. volume': '13657'}, '2025-05-29 11:30:00': {'1. open': '258.8200', '2. high': '258.8200', '3. low': '257.9000', '4. close': '258.1100', '5. volume': '23224'}, '2025-05-29 11:25:00': {'1. open': '258.5550', '2. high': '258.9800', '3. low': '258.5300', '4. close': '258.8900', '5. volume': '18819'}, '2025-05-29 11:20:00': {'1. open': '258.2700', '2. high': '258.6500', '3. low': '258.2600', '4. close': '258.5702', '5. volume': '15690'}, '2025-05-29 11:15:00': {'1. open': '258.3200', '2. high': '258.5000', '3. low': '258.2414', '4. close': '258.2900', '5. volume': '12881'}, '2025-05-29 11:10:00': {'1. open': '258.6250', '2. high': '258.8000', '3. low': '258.2550', '4. close': '258.2550', '5. volume': '15300'}, '2025-05-29 11:05:00': {'1. open': '258.4300', '2. high': '258.6571', '3. low': '258.4300', '4. close': '258.6250', '5. volume': '14757'}, '2025-05-29 11:00:00': {'1. open': '258.8100', '2. high': '258.8100', '3. low': '258.2200', '4. close': '258.4200', '5. volume': '17877'}, '2025-05-29 10:55:00': {'1. open': '258.4400', '2. high': '258.8300', '3. low': '258.4400', '4. close': '258.7866', '5. volume': '19987'}, '2025-05-29 10:50:00': {'1. open': '258.4150', '2. high': '258.6000', '3. low': '258.3600', '4. close': '258.5000', '5. volume': '17660'}, '2025-05-29 10:45:00': {'1. open': '258.2650', '2. high': '258.4700', '3. low': '258.2600', '4. close': '258.4050', '5. volume': '12980'}, '2025-05-29 10:40:00': {'1. open': '258.6400', '2. high': '258.6400', '3. low': '258.1500', '4. close': '258.3150', '5. volume': '14845'}, '2025-05-29 10:35:00': {'1. open': '258.4350', '2. high': '259.2000', '3. low': '258.4350', '4. close': '258.6500', '5. volume': '21483'}, '2025-05-29 10:30:00': {'1. open': '258.7500', '2. high': '259.0350', '3. low': '258.3600', '4. close': '258.4350', '5. volume': '19236'}, '2025-05-29 10:25:00': {'1. open': '258.5541', '2. high': '258.9700', '3. low': '258.5541', '4. close': '258.7400', '5. volume': '24741'}}}

In [ ]:
import pandas as pd

df = pd.read_csv("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=TSLA&apikey=BSLRAR2IZ893LHH2&datatype=csv")

In [67]:
print(df.head())

    timestamp    open    high     low   close     volume
0  2025-05-29  365.29  367.71  356.00  358.43   87372938
1  2025-05-28  364.84  365.00  355.91  356.90   91404309
2  2025-05-27  347.35  363.79  347.32  362.89  120146414
3  2025-05-23  337.92  343.18  333.21  339.34   84654818
4  2025-05-22  331.90  347.27  331.39  341.04   97113416

In [70]:
ticker_id = 'TSLA'
API_KEY = "IA5j5a8TjMEEQOV9RHe8s7oaKVboVeCp"
print(ticker_id)
url = f"https://financialmodelingprep.com/stable/historical-chart/5min?symbol={ticker_id}&apikey={API_KEY}"
print(url)
from urllib.request import urlopen
import certifi
import json


response = urlopen(url, cafile=certifi.where())
data = response.read().decode("utf-8")
data = json.loads(data)
print(data)

TSLA
https://financialmodelingprep.com/stable/historical-chart/5min?symbol=TSLA&apikey=IA5j5a8TjMEEQOV9RHe8s7oaKVboVeCp

/var/folders/td/16v_twyd2fq9rhdl5vysffbw0000gn/T/ipykernel_84607/1901761326.py:11: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.
  response = urlopen(url, cafile=certifi.where())

[{'date': '2025-05-29 15:55:00', 'open': 358.455, 'low': 358.26, 'high': 358.89, 'close': 358.39, 'volume': 1692076}, {'date': '2025-05-29 15:50:00', 'open': 358.8, 'low': 357.67, 'high': 359.5, 'close': 358.3955, 'volume': 1189736}, {'date': '2025-05-29 15:45:00', 'open': 357.535, 'low': 357.535, 'high': 358.8, 'close': 358.62, 'volume': 902064}, {'date': '2025-05-29 15:40:00', 'open': 357.59, 'low': 357.25, 'high': 358.09, 'close': 357.57, 'volume': 1057456}, {'date': '2025-05-29 15:35:00', 'open': 357.94, 'low': 357.4922, 'high': 358.0393, 'close': 357.6, 'volume': 580368}, {'date': '2025-05-29 15:30:00', 'open': 358.12, 'low': 357.785, 'high': 358.71, 'close': 357.96, 'volume': 650946}, {'date': '2025-05-29 15:25:00', 'open': 359.11, 'low': 358.035, 'high': 359.3491, 'close': 358.11, 'volume': 676575}, {'date': '2025-05-29 15:20:00', 'open': 358.6, 'low': 358.6, 'high': 359.26, 'close': 359.12, 'volume': 689418}, {'date': '2025-05-29 15:15:00', 'open': 357.6721, 'low': 357.6721, 'high': 358.78, 'close': 358.5615, 'volume': 741279}, {'date': '2025-05-29 15:10:00', 'open': 358, 'low': 357.63, 'high': 358.22, 'close': 357.635, 'volume': 697412}, {'date': '2025-05-29 15:05:00', 'open': 358.94, 'low': 357.829, 'high': 358.94, 'close': 358.0388, 'volume': 780581}, {'date': '2025-05-29 15:00:00', 'open': 358.77, 'low': 358.45, 'high': 359.05, 'close': 358.89, 'volume': 549256}, {'date': '2025-05-29 14:55:00', 'open': 359.53, 'low': 358.37, 'high': 359.86, 'close': 358.76, 'volume': 879038}, {'date': '2025-05-29 14:50:00', 'open': 359.065, 'low': 359.065, 'high': 359.74, 'close': 359.565, 'volume': 595699}, {'date': '2025-05-29 14:45:00', 'open': 358.735, 'low': 358.735, 'high': 359.7, 'close': 359.05, 'volume': 826799}, {'date': '2025-05-29 14:40:00', 'open': 358.39, 'low': 358.3234, 'high': 359.07, 'close': 358.73, 'volume': 742994}, {'date': '2025-05-29 14:35:00', 'open': 358.185, 'low': 357.93, 'high': 358.53, 'close': 358.42, 'volume': 509558}, {'date': '2025-05-29 14:30:00', 'open': 357.32, 'low': 357.32, 'high': 358.24, 'close': 358.13, 'volume': 606214}, {'date': '2025-05-29 14:25:00', 'open': 356.72, 'low': 356.17, 'high': 357.4876, 'close': 357.27, 'volume': 775586}, {'date': '2025-05-29 14:20:00', 'open': 357.151, 'low': 356.54, 'high': 357.39, 'close': 356.75, 'volume': 810632}, {'date': '2025-05-29 14:15:00', 'open': 358.31, 'low': 357.17, 'high': 358.5145, 'close': 357.17, 'volume': 788258}, {'date': '2025-05-29 14:10:00', 'open': 358.37, 'low': 357.73, 'high': 358.6, 'close': 358.4, 'volume': 824190}, {'date': '2025-05-29 14:05:00', 'open': 356.9, 'low': 356.78, 'high': 358.52, 'close': 358.4327, 'volume': 1129809}, {'date': '2025-05-29 14:00:00', 'open': 356.8595, 'low': 356.71, 'high': 357.45, 'close': 357, 'volume': 925511}, {'date': '2025-05-29 13:55:00', 'open': 357.9143, 'low': 356.1169, 'high': 357.96, 'close': 356.871, 'volume': 1742155}, {'date': '2025-05-29 13:50:00', 'open': 358.6, 'low': 357.76, 'high': 358.82, 'close': 357.985, 'volume': 1611154}, {'date': '2025-05-29 13:45:00', 'open': 361.52, 'low': 358.4108, 'high': 361.52, 'close': 358.53, 'volume': 1428786}, {'date': '2025-05-29 13:40:00', 'open': 362.16, 'low': 361.51, 'high': 362.3783, 'close': 361.52, 'volume': 481289}, {'date': '2025-05-29 13:35:00', 'open': 361.61, 'low': 361.6, 'high': 362.2858, 'close': 362.2858, 'volume': 590764}, {'date': '2025-05-29 13:30:00', 'open': 361.02, 'low': 360.9201, 'high': 361.82, 'close': 361.66, 'volume': 595137}, {'date': '2025-05-29 13:25:00', 'open': 361.345, 'low': 360.69, 'high': 361.4875, 'close': 361.11, 'volume': 615463}, {'date': '2025-05-29 13:20:00', 'open': 361.51, 'low': 361.3, 'high': 361.98, 'close': 361.3, 'volume': 463254}, {'date': '2025-05-29 13:15:00', 'open': 361.73, 'low': 361.22, 'high': 361.9582, 'close': 361.48, 'volume': 567213}, {'date': '2025-05-29 13:10:00', 'open': 361.62, 'low': 361.5221, 'high': 361.9254, 'close': 361.675, 'volume': 449957}, {'date': '2025-05-29 13:05:00', 'open': 362.1, 'low': 361.41, 'high': 362.14, 'close': 361.6, 'volume': 664123}, {'date': '2025-05-29 13:00:00', 'open': 362.58, 'low': 362.02, 'high': 362.7797, 'close': 362.02, 'volume': 518812}, {'date': '2025-05-29 12:55:00', 'open': 362.33, 'low': 362.32, 'high': 363.142, 'close': 362.645, 'volume': 515434}, {'date': '2025-05-29 12:50:00', 'open': 362.9, 'low': 362.1, 'high': 363.24, 'close': 362.39, 'volume': 600263}, {'date': '2025-05-29 12:45:00', 'open': 363.12, 'low': 362.87, 'high': 363.46, 'close': 362.93, 'volume': 517837}, {'date': '2025-05-29 12:40:00', 'open': 362.62, 'low': 362.54, 'high': 363.38, 'close': 363.14, 'volume': 476500}, {'date': '2025-05-29 12:35:00', 'open': 363.205, 'low': 362.57, 'high': 363.5, 'close': 362.7, 'volume': 645840}, {'date': '2025-05-29 12:30:00', 'open': 362.44, 'low': 362.44, 'high': 363.38, 'close': 363.27, 'volume': 653894}, {'date': '2025-05-29 12:25:00', 'open': 362.32, 'low': 362.27, 'high': 362.9, 'close': 362.48, 'volume': 487823}, {'date': '2025-05-29 12:20:00', 'open': 362.275, 'low': 362.275, 'high': 362.84, 'close': 362.3, 'volume': 606838}, {'date': '2025-05-29 12:15:00', 'open': 361.88, 'low': 361.88, 'high': 362.62, 'close': 362.27, 'volume': 682224}, {'date': '2025-05-29 12:10:00', 'open': 361.1608, 'low': 361.01, 'high': 361.9794, 'close': 361.835, 'volume': 693012}, {'date': '2025-05-29 12:05:00', 'open': 360.95, 'low': 360.7837, 'high': 361.62, 'close': 361.13, 'volume': 613433}, {'date': '2025-05-29 12:00:00', 'open': 361.34, 'low': 360.48, 'high': 361.56, 'close': 360.93, 'volume': 1179265}, {'date': '2025-05-29 11:55:00', 'open': 364.031, 'low': 360.84, 'high': 364.17, 'close': 361.23, 'volume': 1366683}, {'date': '2025-05-29 11:50:00', 'open': 362.89, 'low': 362.845, 'high': 364.245, 'close': 364.04, 'volume': 947779}, {'date': '2025-05-29 11:45:00', 'open': 362.6375, 'low': 362.57, 'high': 363.3, 'close': 362.82, 'volume': 447308}, {'date': '2025-05-29 11:40:00', 'open': 362.73, 'low': 362.63, 'high': 363.27, 'close': 362.66, 'volume': 497116}, {'date': '2025-05-29 11:35:00', 'open': 363.22, 'low': 362.29, 'high': 363.33, 'close': 362.72, 'volume': 639457}, {'date': '2025-05-29 11:30:00', 'open': 364.0445, 'low': 362.97, 'high': 364.1072, 'close': 363.13, 'volume': 781019}, {'date': '2025-05-29 11:25:00', 'open': 363.024, 'low': 362.8, 'high': 364.1, 'close': 363.983, 'volume': 946543}, {'date': '2025-05-29 11:20:00', 'open': 362, 'low': 361.94, 'high': 363.0995, 'close': 363.09, 'volume': 566805}, {'date': '2025-05-29 11:15:00', 'open': 362.47, 'low': 361.9, 'high': 363.19, 'close': 361.9, 'volume': 892830}, {'date': '2025-05-29 11:10:00', 'open': 363.14, 'low': 362.29, 'high': 363.81, 'close': 362.48, 'volume': 878405}, {'date': '2025-05-29 11:05:00', 'open': 363.06, 'low': 362.64, 'high': 363.6, 'close': 363.17, 'volume': 705928}, {'date': '2025-05-29 11:00:00', 'open': 363.45, 'low': 362.695, 'high': 363.58, 'close': 363.07, 'volume': 915687}, {'date': '2025-05-29 10:55:00', 'open': 363.62, 'low': 363.04, 'high': 363.63, 'close': 363.07, 'volume': 137086}, {'date': '2025-05-29 10:50:00', 'open': 364.05, 'low': 363.26, 'high': 364.07, 'close': 363.59, 'volume': 1062707}, {'date': '2025-05-29 10:45:00', 'open': 364.27, 'low': 363.85, 'high': 364.72, 'close': 364.05, 'volume': 1274594}, {'date': '2025-05-29 10:40:00', 'open': 363.87, 'low': 363, 'high': 364.46, 'close': 364.25, 'volume': 1350602}, {'date': '2025-05-29 10:35:00', 'open': 362.53, 'low': 362.3, 'high': 363.97, 'close': 363.91, 'volume': 1397454}, {'date': '2025-05-29 10:30:00', 'open': 361.97, 'low': 361.75, 'high': 363.06, 'close': 362.54, 'volume': 1397361}, {'date': '2025-05-29 10:25:00', 'open': 361.2, 'low': 360.67, 'high': 362.1, 'close': 362.02, 'volume': 1013485}, {'date': '2025-05-29 10:20:00', 'open': 361.01, 'low': 360.42, 'high': 361.75, 'close': 361.22, 'volume': 922787}, {'date': '2025-05-29 10:15:00', 'open': 360.98, 'low': 360.68, 'high': 361.98, 'close': 361.04, 'volume': 1397445}, {'date': '2025-05-29 10:10:00', 'open': 360.49, 'low': 359.45, 'high': 361.34, 'close': 360.93, 'volume': 2005009}, {'date': '2025-05-29 10:05:00', 'open': 363.11, 'low': 360.18, 'high': 363.32, 'close': 360.4, 'volume': 2166121}, {'date': '2025-05-29 10:00:00', 'open': 364.15, 'low': 362.86, 'high': 364.39, 'close': 363.06, 'volume': 1349942}, {'date': '2025-05-29 09:55:00', 'open': 365.06, 'low': 363.7, 'high': 365.49, 'close': 364.28, 'volume': 1377965}, {'date': '2025-05-29 09:50:00', 'open': 363.22, 'low': 362.55, 'high': 365.68, 'close': 364.99, 'volume': 2125622}, {'date': '2025-05-29 09:45:00', 'open': 364.05, 'low': 363.08, 'high': 365.88, 'close': 363.25, 'volume': 2156035}, {'date': '2025-05-29 09:40:00', 'open': 363.94, 'low': 363.45, 'high': 365.33, 'close': 363.99, 'volume': 2010688}, {'date': '2025-05-29 09:35:00', 'open': 365.04, 'low': 363.49, 'high': 365.95, 'close': 363.9, 'volume': 2374256}, {'date': '2025-05-29 09:30:00', 'open': 365.29, 'low': 363.78, 'high': 367.72, 'close': 365.03, 'volume': 8115430}, {'date': '2025-05-28 15:55:00', 'open': 356.63, 'low': 356.12, 'high': 358.01, 'close': 356.76, 'volume': 2269638}, {'date': '2025-05-28 15:50:00', 'open': 358.2, 'low': 355.9, 'high': 358.36, 'close': 356.63, 'volume': 1575697}, {'date': '2025-05-28 15:45:00', 'open': 357.97, 'low': 356.94, 'high': 358.45, 'close': 358.24, 'volume': 1173217}, {'date': '2025-05-28 15:40:00', 'open': 358.32, 'low': 357.49, 'high': 358.71, 'close': 357.98, 'volume': 1127197}, {'date': '2025-05-28 15:35:00', 'open': 358.8, 'low': 358.21, 'high': 358.92, 'close': 358.3, 'volume': 834364}, {'date': '2025-05-28 15:30:00', 'open': 359, 'low': 358.66, 'high': 359.09, 'close': 358.85, 'volume': 612275}, {'date': '2025-05-28 15:25:00', 'open': 359.2, 'low': 358.87, 'high': 359.58, 'close': 359.03, 'volume': 626724}, {'date': '2025-05-28 15:20:00', 'open': 359.52, 'low': 358.9, 'high': 359.62, 'close': 359.1, 'volume': 556489}, {'date': '2025-05-28 15:15:00', 'open': 359.73, 'low': 358.75, 'high': 359.96, 'close': 359.59, 'volume': 772361}, {'date': '2025-05-28 15:10:00', 'open': 359.87, 'low': 359.01, 'high': 360.24, 'close': 359.68, 'volume': 962430}, {'date': '2025-05-28 15:05:00', 'open': 359.51, 'low': 358.91, 'high': 360.14, 'close': 359.9, 'volume': 842483}, {'date': '2025-05-28 15:00:00', 'open': 358.77, 'low': 358.48, 'high': 359.6, 'close': 359.48, 'volume': 989562}, {'date': '2025-05-28 14:55:00', 'open': 357.74, 'low': 357.54, 'high': 359.1, 'close': 358.79, 'volume': 1229292}, {'date': '2025-05-28 14:50:00', 'open': 360.01, 'low': 357.38, 'high': 360.26, 'close': 357.7, 'volume': 1996587}, {'date': '2025-05-28 14:45:00', 'open': 361.2, 'low': 359.81, 'high': 361.31, 'close': 360, 'volume': 873837}, {'date': '2025-05-28 14:40:00', 'open': 361.28, 'low': 361.04, 'high': 361.52, 'close': 361.18, 'volume': 429706}, {'date': '2025-05-28 14:35:00', 'open': 360.89, 'low': 360.76, 'high': 361.46, 'close': 361.25, 'volume': 671336}, {'date': '2025-05-28 14:30:00', 'open': 361.43, 'low': 360.73, 'high': 361.69, 'close': 360.89, 'volume': 971875}, {'date': '2025-05-28 14:25:00', 'open': 361.67, 'low': 361.35, 'high': 361.7, 'close': 361.48, 'volume': 501414}, {'date': '2025-05-28 14:20:00', 'open': 362.22, 'low': 361.28, 'high': 362.22, 'close': 361.7, 'volume': 969849}, {'date': '2025-05-28 14:15:00', 'open': 363.24, 'low': 362.14, 'high': 363.29, 'close': 362.22, 'volume': 673802}, {'date': '2025-05-28 14:10:00', 'open': 363.51, 'low': 363.08, 'high': 363.87, 'close': 363.25, 'volume': 731938}, {'date': '2025-05-28 14:05:00', 'open': 363.34, 'low': 363.11, 'high': 363.67, 'close': 363.5, 'volume': 787916}, {'date': '2025-05-28 14:00:00', 'open': 362.66, 'low': 362.2, 'high': 364, 'close': 363.37, 'volume': 987570}, {'date': '2025-05-28 13:55:00', 'open': 362.7, 'low': 362.6, 'high': 363, 'close': 362.65, 'volume': 403129}, {'date': '2025-05-28 13:50:00', 'open': 362.73, 'low': 362.31, 'high': 362.79, 'close': 362.67, 'volume': 411419}, {'date': '2025-05-28 13:45:00', 'open': 362.6, 'low': 362.57, 'high': 363.11, 'close': 362.74, 'volume': 532501}, {'date': '2025-05-28 13:40:00', 'open': 362.69, 'low': 362.33, 'high': 362.91, 'close': 362.63, 'volume': 425060}, {'date': '2025-05-28 13:35:00', 'open': 362.33, 'low': 362.24, 'high': 362.94, 'close': 362.68, 'volume': 604003}, {'date': '2025-05-28 13:30:00', 'open': 362.57, 'low': 362, 'high': 362.65, 'close': 362.38, 'volume': 461064}, {'date': '2025-05-28 13:25:00', 'open': 362.57, 'low': 362.25, 'high': 362.77, 'close': 362.61, 'volume': 444971}, {'date': '2025-05-28 13:20:00', 'open': 362.62, 'low': 362.29, 'high': 362.87, 'close': 362.58, 'volume': 515745}, {'date': '2025-05-28 13:15:00', 'open': 361.94, 'low': 361.9, 'high': 362.75, 'close': 362.6, 'volume': 620694}, {'date': '2025-05-28 13:10:00', 'open': 361.47, 'low': 361.39, 'high': 362.31, 'close': 361.92, 'volume': 638002}, {'date': '2025-05-28 13:05:00', 'open': 361.31, 'low': 361.1, 'high': 361.88, 'close': 361.46, 'volume': 472301}, {'date': '2025-05-28 13:00:00', 'open': 361.4, 'low': 361.1, 'high': 361.76, 'close': 361.29, 'volume': 483156}, {'date': '2025-05-28 12:55:00', 'open': 361.84, 'low': 361.15, 'high': 362.03, 'close': 361.36, 'volume': 493195}, {'date': '2025-05-28 12:50:00', 'open': 361.88, 'low': 361.69, 'high': 362.31, 'close': 361.83, 'volume': 649786}, {'date': '2025-05-28 12:45:00', 'open': 361.06, 'low': 360.9, 'high': 362.06, 'close': 361.89, 'volume': 691376}, {'date': '2025-05-28 12:40:00', 'open': 360.91, 'low': 360.89, 'high': 361.43, 'close': 361.05, 'volume': 446201}, {'date': '2025-05-28 12:35:00', 'open': 360.95, 'low': 360.51, 'high': 361.18, 'close': 360.89, 'volume': 624445}, {'date': '2025-05-28 12:30:00', 'open': 361.1, 'low': 360.92, 'high': 361.3, 'close': 360.95, 'volume': 388088}, {'date': '2025-05-28 12:25:00', 'open': 361.44, 'low': 360.94, 'high': 361.74, 'close': 361.13, 'volume': 609758}, {'date': '2025-05-28 12:20:00', 'open': 361.24, 'low': 361.05, 'high': 361.57, 'close': 361.48, 'volume': 509988}, {'date': '2025-05-28 12:15:00', 'open': 361.15, 'low': 360.8, 'high': 361.36, 'close': 361.21, 'volume': 580977}, {'date': '2025-05-28 12:10:00', 'open': 361.27, 'low': 361.03, 'high': 361.46, 'close': 361.16, 'volume': 465304}, {'date': '2025-05-28 12:05:00', 'open': 361.7, 'low': 361.07, 'high': 361.88, 'close': 361.29, 'volume': 592163}, {'date': '2025-05-28 12:00:00', 'open': 361.05, 'low': 361.05, 'high': 361.82, 'close': 361.71, 'volume': 648427}, {'date': '2025-05-28 11:55:00', 'open': 361.75, 'low': 360.93, 'high': 361.9, 'close': 361.02, 'volume': 816361}, {'date': '2025-05-28 11:50:00', 'open': 362.14, 'low': 361.68, 'high': 362.34, 'close': 361.78, 'volume': 557074}, {'date': '2025-05-28 11:45:00', 'open': 362.91, 'low': 362.14, 'high': 362.95, 'close': 362.16, 'volume': 485339}, {'date': '2025-05-28 11:40:00', 'open': 362.69, 'low': 362.01, 'high': 362.93, 'close': 362.88, 'volume': 703762}, {'date': '2025-05-28 11:35:00', 'open': 362.96, 'low': 362.53, 'high': 363.37, 'close': 362.7, 'volume': 754803}, {'date': '2025-05-28 11:30:00', 'open': 362.98, 'low': 362.42, 'high': 363.2, 'close': 362.96, 'volume': 658762}, {'date': '2025-05-28 11:25:00', 'open': 362.88, 'low': 362.41, 'high': 363.36, 'close': 363, 'volume': 930379}, {'date': '2025-05-28 11:20:00', 'open': 362.49, 'low': 362.01, 'high': 363.15, 'close': 362.89, 'volume': 1040158}, {'date': '2025-05-28 11:15:00', 'open': 360.89, 'low': 360.7, 'high': 362.73, 'close': 362.45, 'volume': 1098493}, {'date': '2025-05-28 11:10:00', 'open': 361.01, 'low': 360.44, 'high': 361.4, 'close': 360.84, 'volume': 726023}, {'date': '2025-05-28 11:05:00', 'open': 361.53, 'low': 360.82, 'high': 361.77, 'close': 361.02, 'volume': 702237}, {'date': '2025-05-28 11:00:00', 'open': 361.17, 'low': 361.01, 'high': 361.69, 'close': 361.54, 'volume': 626165}, {'date': '2025-05-28 10:55:00', 'open': 361.77, 'low': 361.02, 'high': 362.31, 'close': 361.15, 'volume': 784394}, {'date': '2025-05-28 10:50:00', 'open': 362.05, 'low': 361.52, 'high': 362.39, 'close': 361.7, 'volume': 858144}, {'date': '2025-05-28 10:45:00', 'open': 361.71, 'low': 361.44, 'high': 362.7, 'close': 362.06, 'volume': 892448}, {'date': '2025-05-28 10:40:00', 'open': 361.08, 'low': 360.88, 'high': 362.29, 'close': 361.73, 'volume': 1045337}, {'date': '2025-05-28 10:35:00', 'open': 361.25, 'low': 360.59, 'high': 361.5, 'close': 361.02, 'volume': 963050}, {'date': '2025-05-28 10:30:00', 'open': 361.68, 'low': 360.96, 'high': 362.19, 'close': 361.24, 'volume': 83459}, {'date': '2025-05-28 10:25:00', 'open': 362.04, 'low': 361.15, 'high': 362.36, 'close': 361.63, 'volume': 912561}, {'date': '2025-05-28 10:20:00', 'open': 362.92, 'low': 360.9, 'high': 363.24, 'close': 362.09, 'volume': 1769446}, {'date': '2025-05-28 10:15:00', 'open': 363.95, 'low': 362.73, 'high': 364.59, 'close': 362.93, 'volume': 2394936}, {'date': '2025-05-28 10:10:00', 'open': 362.36, 'low': 361.99, 'high': 363.95, 'close': 363.93, 'volume': 2280801}, {'date': '2025-05-28 10:05:00', 'open': 362.22, 'low': 361.02, 'high': 362.94, 'close': 362.43, 'volume': 1562559}, {'date': '2025-05-28 10:00:00', 'open': 361.09, 'low': 360.98, 'high': 362.55, 'close': 362.25, 'volume': 1594292}, {'date': '2025-05-28 09:55:00', 'open': 361.01, 'low': 360.18, 'high': 361.97, 'close': 361, 'volume': 1957887}, {'date': '2025-05-28 09:50:00', 'open': 359.45, 'low': 358.64, 'high': 361.3, 'close': 361.05, 'volume': 2435687}, {'date': '2025-05-28 09:45:00', 'open': 360.86, 'low': 359.21, 'high': 361.32, 'close': 359.42, 'volume': 2620279}, {'date': '2025-05-28 09:40:00', 'open': 362.41, 'low': 360.02, 'high': 362.55, 'close': 360.82, 'volume': 2540339}, {'date': '2025-05-28 09:35:00', 'open': 361.51, 'low': 361.11, 'high': 362.89, 'close': 362.4, 'volume': 2835586}, {'date': '2025-05-28 09:30:00', 'open': 364.89, 'low': 360.54, 'high': 364.89, 'close': 361.62, 'volume': 8575598}, {'date': '2025-05-27 15:55:00', 'open': 362.1, 'low': 361.8, 'high': 363, 'close': 362.75, 'volume': 3707489}, {'date': '2025-05-27 15:50:00', 'open': 360.6, 'low': 359.23, 'high': 362.39, 'close': 362.02, 'volume': 2331237}, {'date': '2025-05-27 15:45:00', 'open': 360.39, 'low': 360.27, 'high': 361.05, 'close': 360.59, 'volume': 1350953}, {'date': '2025-05-27 15:40:00', 'open': 358.85, 'low': 358.78, 'high': 360.52, 'close': 360.4, 'volume': 1568537}, {'date': '2025-05-27 15:35:00', 'open': 359.43, 'low': 357.8, 'high': 359.46, 'close': 358.8, 'volume': 1627712}, {'date': '2025-05-27 15:30:00', 'open': 359.89, 'low': 358.88, 'high': 359.91, 'close': 359.44, 'volume': 937289}, {'date': '2025-05-27 15:25:00', 'open': 359.98, 'low': 359.71, 'high': 360.35, 'close': 359.89, 'volume': 1049537}, {'date': '2025-05-27 15:20:00', 'open': 359.15, 'low': 359, 'high': 360.23, 'close': 359.98, 'volume': 1258141}, {'date': '2025-05-27 15:15:00', 'open': 359.06, 'low': 358.63, 'high': 359.29, 'close': 359.14, 'volume': 1400958}, {'date': '2025-05-27 15:10:00', 'open': 359.23, 'low': 358.6, 'high': 359.38, 'close': 359.04, 'volume': 1030674}, {'date': '2025-05-27 15:05:00', 'open': 359.06, 'low': 358.8, 'high': 359.38, 'close': 359.24, 'volume': 1047617}, {'date': '2025-05-27 15:00:00', 'open': 359.67, 'low': 358.68, 'high': 359.67, 'close': 359.06, 'volume': 1288335}, {'date': '2025-05-27 14:55:00', 'open': 360.95, 'low': 359.5, 'high': 360.96, 'close': 359.75, 'volume': 1273074}, {'date': '2025-05-27 14:50:00', 'open': 361.14, 'low': 360.5, 'high': 361.63, 'close': 360.95, 'volume': 831429}, {'date': '2025-05-27 14:45:00', 'open': 360.9, 'low': 360.75, 'high': 361.55, 'close': 361.15, 'volume': 901958}, {'date': '2025-05-27 14:40:00', 'open': 361.74, 'low': 360.22, 'high': 361.83, 'close': 360.9, 'volume': 1466931}, {'date': '2025-05-27 14:35:00', 'open': 362.07, 'low': 361.7, 'high': 362.47, 'close': 361.72, 'volume': 775025}, {'date': '2025-05-27 14:30:00', 'open': 362, 'low': 361.75, 'high': 362.23, 'cl

In [69]:
ticker_id = 'TSLA'
API_KEY = "IA5j5a8TjMEEQOV9RHe8s7oaKVboVeCp"

url = f"https://financialmodelingprep.com/stable/historical-price-eod/non-split-adjusted?symbol={ticker_id}&apikey={API_KEY}"
response = urlopen(url, cafile=certifi.where())
data = response.read().decode("utf-8")
data = json.loads(data)
df = pd.DataFrame(data)
print(df)

/var/folders/td/16v_twyd2fq9rhdl5vysffbw0000gn/T/ipykernel_84607/1639344083.py:5: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.
  response = urlopen(url, cafile=certifi.where())

     symbol        date  adjOpen  adjHigh  adjLow  adjClose     volume
0      TSLA  2025-05-29   365.29   367.71  356.00    358.43   88545666
1      TSLA  2025-05-28   364.84   365.00  355.91    356.90   91404309
2      TSLA  2025-05-27   347.35   363.79  347.32    362.89  120146414
3      TSLA  2025-05-23   337.92   343.18  333.21    339.34   84654818
4      TSLA  2025-05-22   331.90   347.27  331.39    341.04   97113416
...     ...         ...      ...      ...     ...       ...        ...
1251   TSLA  2020-06-05   877.80   886.50  866.25    885.60    7811900
1252   TSLA  2020-06-04   889.95   895.80  858.45    864.45    8887700
1253   TSLA  2020-06-03   888.15   897.90  880.05    882.90    7949500
1254   TSLA  2020-06-02   894.75   908.70  871.05    881.55   13565600
1255   TSLA  2020-06-01   858.00   898.95  854.10    898.05   14939500

[1256 rows x 7 columns]

In [ ]:
df = df.rename(columns={
"date": "Datetime",
"open": "Open",
"low": "Low",
"high": "High",
"close": "Close",
"volume": "Volume",
})

df['ticker_id'] = ticker_id
df['Adj High'] = df['High']
df['Adj Close'] = df['Close']
df['Adj Low'] = df['Low']
df['Adj Open'] = df['Open']

In [2]:
import requests
import json
import os # 用于处理文件路径

# --- 配置参数 ---
BASE_URL = "https://engine.invesdo.co:80/api/web/market/overview"
PAYLOAD = {
    "user_id": 123,
    "user_name": "test_user",
    "user_language": "en"
}
HEADERS = {
    "Content-Type": "application/json"
}

CA_CERT_PATH = "/Users/liuda/Library/CloudStorage/Dropbox/shareit/code/trading/Agent-engines-python/config/pem_v2/engine.invesdo.co.cer" # <--- 修改这里!

response = requests.post(
	BASE_URL,
	headers=HEADERS,
	data=json.dumps(PAYLOAD), # 将 Python 字典转换为 JSON 字符串
	verify=CA_CERT_PATH,      # 启用 SSL 证书验证，并指定 CA 证书路径
	timeout=600
)

print(response)
print(response.text)

SSLError: HTTPSConnectionPool(host='engine.invesdo.co', port=80): Max retries exceeded with url: /api/web/market/overview (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1017)')))

In [17]:
import pandas as pd

ticker_data = pd.read_csv("/Users/liuda/Desktop/MSTR.csv")
ticker_data['Date'] = pd.to_datetime(ticker_data['Date'])
ticker_data.set_index('Date', inplace=True)

print(ticker_data.shape)
import talib
talib.EMA(ticker_data['Adj Close'], timeperiod=144)

(364, 236)

Date
2024-06-05           NaN
2024-06-06           NaN
2024-06-07           NaN
2024-06-08           NaN
2024-06-09           NaN
                 ...
2025-05-30    336.736891
2025-05-31    337.182727
2025-06-01    337.622414
2025-06-02    338.100312
2025-06-03    338.780721
Length: 364, dtype: float64

In [16]:
import pandas as pd

ticker_data = pd.read_csv("/Users/liuda/Desktop/MSTR.csv")
ticker_data = ticker_data[ticker_data['Date'] >= '2024-06-10']

ticker_data['Date'] = pd.to_datetime(ticker_data['Date'])
ticker_data.set_index('Date', inplace=True)
print(ticker_data.shape)

import talib
talib.EMA(ticker_data['Adj Close'], timeperiod=144)

(359, 236)

Date
2024-06-10           NaN
2024-06-11           NaN
2024-06-12           NaN
2024-06-13           NaN
2024-06-14           NaN
                 ...
2025-05-30    336.561724
2025-05-31    337.009976
2025-06-01    337.452045
2025-06-02    337.932293
2025-06-03    338.615020
Length: 359, dtype: float64