In [31]:
from futu import *
import pandas_ta as ta
import pandas as pd
import glob

import json
import talib

from collections import OrderedDict
import numpy as np

In [32]:
last_date = datetime.today() - timedelta(days=1)
last_date = last_date.strftime('%Y-%m-%d')

In [33]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', None)

In [34]:
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111)

2025-07-04 15:15:51,248 | 36440 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=7, host=127.0.0.1, port=11111, user_id=11541642

In [35]:
# quote_ctx.close()

In [ ]:
def get_watch_tickers(group_name="特别关注", quote_ctx=None):
	if quote_ctx is None:
		raise ValueError("quote_ctx cannot be None")
	ret_code, heart_watch_list = quote_ctx.get_user_security(group_name=group_name)

	heart_watch_list = heart_watch_list[heart_watch_list['stock_type'] == 'STOCK']
	heart_watch_list = heart_watch_list[heart_watch_list['code'].str.startswith('HK')]

	watch_df = heart_watch_list[['code']]
	watch_df = watch_df.rename(columns={'code': 'ticker_id'})

	return watch_df

In [38]:
trd_ctx = OpenSecTradeContext(filter_trdmarket=TrdMarket.HK, host='127.0.0.1', port=11111, security_firm=SecurityFirm.FUTUSECURITIES)

ret, position_df = trd_ctx.position_list_query()

position_tickers = position_df[['code']]
position_tickers = position_tickers.rename(columns={'code': 'ticker_id'})

2025-07-04 15:15:57,891 | 36440 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=8, host=127.0.0.1, port=11111, user_id=11541642

In [39]:
display(position_df)

,code,stock_name,position_market,qty,can_sell_qty,cost_price,cost_price_valid,average_cost,diluted_cost,market_val,...,today_buy_qty,today_buy_val,today_pl_val,today_trd_val,today_sell_qty,today_sell_val,position_side,unrealized_pl,realized_pl,currency
0,HK.03690,美团-W,HK,500.0,500.0,132.500,True,132.500,132.500,60350.0,...,0.0,0.0,-1050.0,0.0,0.0,0.0,LONG,-5900.0000,0.0000,HKD
1,HK.01788,国泰君安国际,HK,10000.0,10000.0,4.730,True,4.730,4.730,42800.0,...,0.0,0.0,4200.0,0.0,0.0,0.0,LONG,-4500.0000,0.0000,HKD
2,HK.01398,工商银行,HK,5000.0,5000.0,6.360,True,6.360,6.360,30700.0,...,0.0,0.0,250.0,0.0,0.0,0.0,LONG,-1100.0000,0.0000,HKD
3,HK.01211,比亚迪股份,HK,1000.0,1000.0,265.600,True,265.600,265.600,121300.0,...,0.0,0.0,-1700.0,0.0,0.0,0.0,LONG,-144300.0000,0.0000,HKD
4,HK.00700,腾讯控股,HK,283.0,283.0,62.259,True,267.338,62.259,140594.4,...,0.0,0.0,-1188.6,0.0,0.0,0.0,LONG,64937.6635,556180.7365,HKD

In [40]:
def get_plate_stock(group_name, quote_ctx=None):
    ret, result_df = quote_ctx.get_plate_stock(group_name)  # 恒指成分
    result_df = result_df[['code']]
    result_df = result_df.rename(columns={'code': 'ticker_id'})

    return result_df

hengsheng_df = get_plate_stock('HK.HSI Constituent Stocks', quote_ctx)
hot_df = get_plate_stock('HK.LIST1600', quote_ctx)
bank_df = get_plate_stock("HK.LIST1079", quote_ctx)

biology_df = get_plate_stock("HK.LIST1050", quote_ctx)
medicine_df = get_plate_stock("HK.LIST1067", quote_ctx)
car_df = get_plate_stock("HK.LIST1067", quote_ctx)

In [ ]:
local_files = glob.glob('./data/*.csv')
local_files = [item.replace('.csv', '').replace('./data/', '') for item in local_files]

local_tickers = pd.read_csv('./conf/ticker_id.csv')
local_tickers = pd.concat([local_tickers, pd.DataFrame({'ticker_id': local_files})], ignore_index=True)

watch_df_sep = get_watch_tickers(group_name="特别关注", quote_ctx=quote_ctx)
watch_df_hk = get_watch_tickers(group_name="港股", quote_ctx=quote_ctx)
watch_df_a = get_watch_tickers(group_name="沪深", quote_ctx=quote_ctx)

config_tickers = pd.concat([local_tickers, 
			    hengsheng_df, bank_df, hot_df, biology_df, 
			    medicine_df, car_df, position_tickers,
			    watch_df_sep, watch_df_hk, watch_df_a], ignore_index=True)
config_tickers = config_tickers.drop_duplicates(subset=['ticker_id'])

config_tickers.to_csv('./conf/ticker_id.csv', index=False, encoding='utf-8-sig')

display(config_tickers.shape)

TypeError: string indices must be integers

In [ ]:
def download_ticker_ohcl(ticker_id):
	output_file = f"./data/{ticker_id}.csv"
	max_date = None
	curr_date = datetime.today().date().strftime('%Y-%m-%d')
	last_date = (datetime.today() - timedelta(days=1)).date().strftime('%Y-%m-%d')
	curr_hour = datetime.now().hour
	"""
	if os.path.isfile(output_file):
		data = pd.read_csv(output_file)
		if not data.empty:
			max_date = data['time_key'].max()
			max_date = pd.to_datetime(max_date).strftime('%Y-%m-%d')
			if (curr_hour > 18 and max_date >= curr_date) or (curr_hour <= 18 and max_date >= last_date):  
				# 18点以后，尝试获取今天的数据,18点之前，尝试获取昨天的数据
				return data
	"""

	ret, data, page_req_key = quote_ctx.request_history_kline(
		ticker_id, start='2000-01-01', end='2025-12-31', max_count=10000, session=Session.ALL)
	time.sleep(0.51)   # qps limit 2
	if ret != 0:
		print(f'Error fetching history for {ticker_id}: {data}')
		return None
	
	data.to_csv(output_file, index=False)
	return data

In [43]:
# Initialize an empty DataFrame to store ticker history

df_ohcl = pd.DataFrame({
    key: [] for key in
    ['code', 'name', 'time_key', 'open', 'close', 'high', 'low', 'pe_ratio',
       'turnover_rate', 'volume', 'turnover', 'change_rate', 'last_close']
})

In [44]:
for index, row in config_tickers.iterrows():
    ticker_id = row['ticker_id']
    try:
        curr_history = download_ticker_ohcl(ticker_id)
        if curr_history is not None and not curr_history.empty:
            df_ohcl = pd.concat([df_ohcl, curr_history], axis=0)
            print(f"Processed {ticker_id} {index + 1}/{config_tickers.shape[0]}, {curr_history.shape}, {curr_history['time_key'].max()}")
        else:
            print(f"Processed {ticker_id} {index + 1}/{config_tickers.shape[0]}, ticker_data empty.")
    except Exception as e:
        print(ticker_id, e)

Processed SH.601088 1/732, (2371, 13), 2025-07-04 00:00:00
Processed SH.600585 2/732, (2435, 13), 2025-07-04 00:00:00
Processed SZ.002714 3/732, (2425, 13), 2025-07-04 00:00:00
Processed SH.601899 4/732, (2429, 13), 2025-07-04 00:00:00
Processed SZ.000651 5/732, (2278, 13), 2025-07-04 00:00:00
Processed SZ.000333 6/732, (2385, 13), 2025-07-04 00:00:00
Processed SH.600019 7/732, (2345, 13), 2025-07-04 00:00:00
Processed SH.600010 8/732, (2426, 13), 2025-07-04 00:00:00
Processed SH.600438 9/732, (2360, 13), 2025-07-04 00:00:00
Processed HK.02276 10/732, (869, 13), 2025-07-04 00:00:00
Processed HK.02510 11/732, (164, 13), 2025-07-04 00:00:00
Processed HK.00887 12/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01541 13/732, (448, 13), 2025-07-04 00:00:00
Processed HK.00688 14/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09690 15/732, (434, 13), 2025-07-04 00:00:00
Processed HK.01347 16/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00059 17/732, (2383, 13), 2025-03-31 00:00:00
Processed HK.00717 18/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00267 19/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.06616 20/732, (974, 13), 2025-07-04 00:00:00
Processed HK.06831 21/732, (35, 13), 2025-07-04 00:00:00
Processed HK.01810 22/732, (1720, 13), 2025-07-04 00:00:00
Processed HK.01193 23/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.06603 24/732, (4, 13), 2025-07-04 00:00:00
Processed HK.02465 25/732, (166, 13), 2025-07-04 00:00:00
Processed HK.08606 26/732, (1711, 13), 2025-07-03 00:00:00
Processed HK.01385 27/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09901 28/732, (1143, 13), 2025-07-04 00:00:00
Processed HK.00058 29/732, (2390, 13), 2025-07-04 00:00:00
Processed HK.03380 30/732, (2390, 13), 2025-07-04 00:00:00
Processed HK.00845 31/732, (2387, 13), 2025-03-31 00:00:00
Processed HK.01568 32/732, (2338, 13), 2025-07-04 00:00:00
Processed HK.03800 33/732, (2317, 13), 2025-07-04 00:00:00
Processed HK.02505 34/732, (271, 13), 2025-07-04 00:00:00
Processed HK.08028 35/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00460 36/732, (2299, 13), 2025-07-04 00:00:00
Processed HK.02511 37/732, (373, 13), 2025-07-04 00:00:00
Processed HK.01030 38/732, (2459, 13), 2025-07-04 00:00:00
Processed HK.03633 39/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.01024 40/732, (1081, 13), 2025-07-04 00:00:00
Processed HK.01026 41/732, (2463, 13), 2025-07-03 00:00:00
Processed HK.02507 42/732, (240, 13), 2025-07-04 00:00:00
Processed HK.01797 43/732, (1541, 13), 2025-07-04 00:00:00
Processed HK.00489 44/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.01783 45/732, (1683, 13), 2025-07-04 00:00:00
Processed HK.00884 46/732, (2341, 13), 2025-07-04 00:00:00
Processed HK.09678 47/732, (4, 13), 2025-07-04 00:00:00
Processed HK.09888 48/732, (1051, 13), 2025-07-04 00:00:00
Processed HK.00853 49/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09863 50/732, (676, 13), 2025-07-04 00:00:00
Processed HK.00728 51/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02881 52/732, (257, 13), 2025-07-04 00:00:00
Processed HK.01378 53/732, (2314, 13), 2025-07-04 00:00:00
Processed HK.00066 54/732, (2462, 13), 2025-07-04 00:00:00
Processed HK.00700 55/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.08162 56/732, (2205, 13), 2025-07-04 00:00:00
Processed HK.00258 57/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02473 58/732, (404, 13), 2025-07-04 00:00:00
Processed HK.00270 59/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.06601 60/732, (1060, 13), 2025-07-04 00:00:00
Processed HK.02498 61/732, (366, 13), 2025-07-04 00:00:00
Processed HK.02499 62/732, (403, 13), 2025-07-04 00:00:00
Processed HK.08611 63/732, (1648, 13), 2025-07-04 00:00:00
Processed HK.01621 64/732, (1803, 13), 2025-07-04 00:00:00
Processed HK.03750 65/732, (33, 13), 2025-07-04 00:00:00
Processed HK.03988 66/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.08349 67/732, (1838, 13), 2025-07-04 00:00:00
Processed HK.03383 68/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02076 69/732, (617, 13), 2025-07-04 00:00:00
Processed HK.08201 70/732, (2401, 13), 2025-07-03 00:00:00
Processed HK.01972 71/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02512 72/732, (259, 13), 2025-07-04 00:00:00
Processed HK.02506 73/732, (125, 13), 2025-07-04 00:00:00
Processed HK.02502 74/732, (374, 13), 2025-07-04 00:00:00
Processed HK.00467 75/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02516 76/732, (373, 13), 2025-07-04 00:00:00
Processed HK.81810 77/732, (501, 13), 2025-07-04 00:00:00
Processed HK.01209 78/732, (1121, 13), 2025-07-04 00:00:00
Processed HK.09899 79/732, (879, 13), 2025-07-04 00:00:00
Processed HK.00895 80/732, (2447, 13), 2025-07-04 00:00:00
Processed HK.00881 81/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00659 82/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.09696 83/732, (731, 13), 2025-07-04 00:00:00
Processed HK.02099 84/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09866 85/732, (813, 13), 2025-07-04 00:00:00
Processed HK.02648 86/732, (1, 13), 2025-07-04 00:00:00
Processed HK.08629 87/732, (200, 13), 2025-07-04 00:00:00
Processed HK.02338 88/732, (2462, 13), 2025-07-04 00:00:00
Processed HK.03998 89/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01816 90/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02489 91/732, (373, 13), 2025-07-04 00:00:00
Processed HK.06823 92/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02488 93/732, (2456, 13), 2025-07-04 00:00:00
Processed HK.00512 94/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00274 95/732, (2236, 13), 2025-06-30 00:00:00
Processed HK.02477 96/732, (361, 13), 2025-07-04 00:00:00
Processed HK.00506 97/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01354 98/732, (247, 13), 2025-07-04 00:00:00
Processed HK.00710 99/732, (2458, 13), 2025-07-04 00:00:00
Processed HK.02098 100/732, (2454, 13), 2025-07-04 00:00:00
Processed HK.00857 101/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00880 102/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01208 103/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.00116 104/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01787 105/732, (1661, 13), 2025-07-04 00:00:00
Processed HK.00328 106/732, (2462, 13), 2025-07-04 00:00:00
Processed HK.01988 107/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00300 108/732, (194, 13), 2025-07-04 00:00:00
Processed HK.02517 109/732, (409, 13), 2025-07-04 00:00:00
Processed HK.02503 110/732, (364, 13), 2025-07-04 00:00:00
Processed HK.00314 111/732, (616, 13), 2025-07-04 00:00:00
Processed HK.02515 112/732, (294, 13), 2025-07-04 00:00:00
Processed HK.00302 113/732, (1395, 13), 2025-07-04 00:00:00
Processed HK.00316 114/732, (2450, 13), 2025-07-04 00:00:00
Processed HK.02529 115/732, (278, 13), 2025-07-04 00:00:00
Processed HK.01746 116/732, (1717, 13), 2025-07-04 00:00:00
Processed HK.00666 117/732, (377, 13), 2025-07-04 00:00:00
Processed HK.03347 118/732, (1205, 13), 2025-07-04 00:00:00
Processed HK.03390 119/732, (1283, 13), 2025-07-04 00:00:00
Processed HK.00855 120/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02105 121/732, (494, 13), 2025-07-04 00:00:00
Processed HK.02111 122/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09911 123/732, (1354, 13), 2025-07-04 00:00:00
Processed HK.02688 124/732, (2458, 13), 2025-07-04 00:00:00
Processed HK.00921 125/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02313 126/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.06613 127/732, ticker_data empty.
Processed HK.01801 128/732, (1641, 13), 2025-07-04 00:00:00
Processed HK.03958 129/732, (2211, 13), 2025-07-04 00:00:00
Processed HK.00288 130/732, (2462, 13), 2025-07-04 00:00:00
Processed HK.01800 131/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02312 132/732, (2456, 13), 2025-07-04 00:00:00
Processed HK.06606 133/732, (765, 13), 2024-03-27 00:00:00
Processed HK.02460 134/732, (171, 13), 2025-07-04 00:00:00
Processed HK.02306 135/732, (600, 13), 2025-07-04 00:00:00
Processed HK.00511 136/732, (2445, 13), 2025-07-04 00:00:00
Processed HK.06160 137/732, (1698, 13), 2025-07-04 00:00:00
Processed HK.08401 138/732, (1786, 13), 2025-07-04 00:00:00
Processed HK.01357 139/732, (2101, 13), 2025-07-04 00:00:00
Processed HK.00868 140/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09680 141/732, (242, 13), 2025-07-04 00:00:00
Processed HK.00883 142/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01223 143/732, (2462, 13), 2025-07-04 00:00:00
Processed HK.00101 144/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.06955 145/732, (613, 13), 2025-07-04 00:00:00
Processed HK.06969 146/732, (1225, 13), 2025-07-04 00:00:00
Processed HK.01747 147/732, (1382, 13), 2025-07-04 00:00:00
Processed HK.00317 148/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00303 149/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.08039 150/732, (1835, 13), 2025-06-30 00:00:00
Processed HK.00358 151/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02567 152/732, (176, 13), 2025-07-04 00:00:00
Processed HK.00370 153/732, (2410, 13), 2025-07-04 00:00:00
Processed HK.03692 154/732, (1491, 13), 2025-07-04 00:00:00
Processed HK.06098 155/732, (1729, 13), 2025-07-04 00:00:00
Processed HK.02598 156/732, (309, 13), 2025-07-04 00:00:00
Processed HK.01091 157/732, (2252, 13), 2025-07-04 00:00:00
Processed HK.09618 158/732, (1239, 13), 2025-07-04 00:00:00
Processed HK.00990 159/732, (2459, 13), 2025-07-04 00:00:00
Processed HK.02605 160/732, (18, 13), 2025-07-04 00:00:00
Processed HK.09988 161/732, (1377, 13), 2025-07-04 00:00:00
Processed HK.00012 162/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01318 163/732, (137, 13), 2025-07-04 00:00:00
Processed HK.00006 164/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.02611 165/732, (2003, 13), 2025-07-04 00:00:00
Processed HK.00953 166/732, (2453, 13), 2025-07-04 00:00:00
Processed HK.01132 167/732, (2454, 13), 2025-07-04 00:00:00
Processed HK.01898 168/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01126 169/732, (2461, 13), 2025-07-04 00:00:00
Processed HK.00576 170/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00204 171/732, (2271, 13), 2025-07-04 00:00:00
Processed HK.00588 172/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.08659 173/732, (1224, 13), 2025-07-04 00:00:00
Processed HK.02360 174/732, (1592, 13), 2025-07-04 00:00:00
Processed HK.01133 175/732, (2459, 13), 2025-07-04 00:00:00
Processed HK.01655 176/732, (2004, 13), 2025-07-04 00:00:00
Processed HK.01480 177/732, (2459, 13), 2025-07-04 00:00:00
Processed HK.02610 178/732, (68, 13), 2025-07-04 00:00:00
Processed HK.02162 179/732, (980, 13), 2025-07-04 00:00:00
Processed HK.00013 180/732, (985, 13), 2025-07-04 00:00:00
Processed HK.01443 181/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.02638 182/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01251 183/732, (2405, 13), 2025-07-04 00:00:00
Processed HK.06099 184/732, (2148, 13), 2025-07-04 00:00:00
Processed HK.01090 185/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01709 186/732, (2391, 13), 2025-07-04 00:00:00
Processed HK.02566 187/732, (145, 13), 2025-07-04 00:00:00
Processed HK.03678 188/732, (2338, 13), 2025-07-04 00:00:00
Processed HK.01053 189/732, (2461, 13), 2025-07-04 00:00:00
Processed HK.03888 190/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02228 191/732, (260, 13), 2025-07-04 00:00:00
Processed HK.01723 192/732, (1657, 13), 2025-07-04 00:00:00
Processed HK.01045 193/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02202 194/732, (2453, 13), 2025-07-04 00:00:00
Processed HK.02570 195/732, (139, 13), 2025-07-04 00:00:00
Processed HK.01086 196/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01910 197/732, (2460, 13), 2025-07-04 00:00:00
Processed HK.09633 198/732, (1183, 13), 2025-07-04 00:00:00
Processed HK.00165 199/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02799 200/732, (2189, 13), 2025-07-04 00:00:00
Processed HK.00818 201/732, (2462, 13), 2025-07-04 00:00:00
Processed HK.01333 202/732, (42, 13), 2025-07-04 00:00:00
Processed HK.00763 203/732, (2405, 13), 2025-07-04 00:00:00
Processed HK.00005 204/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00011 205/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00777 206/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00788 207/732, (1698, 13), 2025-07-04 00:00:00
Processed HK.02438 208/732, (293, 13), 2025-07-04 00:00:00
Processed HK.06886 209/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02410 210/732, (213, 13), 2025-07-04 00:00:00
Processed HK.01119 211/732, (1614, 13), 2025-07-04 00:00:00
Processed HK.06676 212/732, (79, 13), 2025-07-04 00:00:00
Processed HK.06110 213/732, (1410, 13), 2025-07-04 00:00:00
Processed HK.06878 214/732, (2326, 13), 2025-03-31 00:00:00
Processed HK.03900 215/732, (2462, 13), 2025-07-04 00:00:00
Processed HK.02388 216/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02405 217/732, (552, 13), 2025-07-04 00:00:00
Processed HK.01497 218/732, (381, 13), 2025-07-04 00:00:00
Processed HK.00945 219/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09961 220/732, (1035, 13), 2025-07-04 00:00:00
Processed HK.01468 221/732, (2436, 13), 2025-07-04 00:00:00
Processed HK.00762 222/732, (2460, 13), 2025-07-04 00:00:00
Processed HK.00992 223/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02149 224/732, (371, 13), 2025-07-04 00:00:00
Processed HK.09626 225/732, (1046, 13), 2025-07-04 00:00:00
Processed HK.02015 226/732, (955, 13), 2025-07-04 00:00:00
Processed HK.03323 227/732, (2462, 13), 2025-07-04 00:00:00
Processed HK.01252 228/732, (2239, 13), 2025-07-04 00:00:00
Processed HK.01911 229/732, (1312, 13), 2025-07-04 00:00:00
Processed HK.01939 230/732, (1647, 13), 2025-07-04 00:00:00
Processed HK.03690 231/732, (1667, 13), 2025-07-04 00:00:00
Processed HK.00399 232/732, (2432, 13), 2025-07-04 00:00:00
Processed HK.01093 233/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.00400 234/732, (2459, 13), 2025-07-04 00:00:00
Processed HK.02217 235/732, (907, 13), 2025-07-04 00:00:00
Processed HK.02565 236/732, (28, 13), 2025-07-04 00:00:00
Processed HK.01044 237/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02559 238/732, (249, 13), 2025-07-04 00:00:00
Processed HK.00376 239/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02549 240/732, (185, 13), 2025-07-04 00:00:00
Processed HK.01929 241/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01083 242/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09636 243/732, (567, 13), 2025-07-04 00:00:00
Processed HK.89988 244/732, (501, 13), 2025-07-04 00:00:00
Processed HK.00612 245/732, (2148, 13), 2025-06-27 00:00:00
Processed HK.02777 246/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.01530 247/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.03333 248/732, (1748, 13), 2024-01-29 00:00:00
Processed HK.08299 249/732, (2077, 13), 2025-07-04 00:00:00
Processed HK.02617 250/732, (9, 13), 2025-07-04 00:00:00
Processed HK.02171 251/732, (993, 13), 2025-07-04 00:00:00
Processed HK.01478 252/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00772 253/732, (1881, 13), 2025-07-04 00:00:00
Processed HK.02603 254/732, (28, 13), 2025-07-04 00:00:00
Processed HK.00014 255/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.01336 256/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.09959 257/732, (1040, 13), 2025-07-04 00:00:00
Processed HK.00941 258/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00799 259/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02373 260/732, (603, 13), 2025-07-04 00:00:00
Processed HK.01108 261/732, (2458, 13), 2025-07-04 00:00:00
Processed HK.02367 262/732, (651, 13), 2025-07-04 00:00:00
Processed HK.00570 263/732, (2452, 13), 2025-07-04 00:00:00
Processed HK.00558 264/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02429 265/732, (408, 13), 2025-07-04 00:00:00
Processed HK.06883 266/732, (6, 13), 2025-07-04 00:00:00
Processed HK.03939 267/732, (2460, 13), 2025-07-04 00:00:00
Processed HK.06855 268/732, (1398, 13), 2025-07-04 00:00:00
Processed HK.01860 269/732, (1611, 13), 2025-07-04 00:00:00
Processed HK.06869 270/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00559 271/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01647 272/732, (2025, 13), 2025-07-04 00:00:00
Processed HK.02400 273/732, (1365, 13), 2025-07-04 00:00:00
Processed HK.01109 274/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00968 275/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02158 276/732, (1096, 13), 2025-07-04 00:00:00
Processed HK.02602 277/732, (676, 13), 2025-07-04 00:00:00
Processed HK.02616 278/732, (1525, 13), 2025-07-04 00:00:00
Processed HK.00001 279/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01243 280/732, (2270, 13), 2025-07-04 00:00:00
Processed HK.01519 281/732, (413, 13), 2025-07-04 00:00:00
Processed HK.08529 282/732, (267, 13), 2025-07-04 00:00:00
Processed HK.00175 283/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01928 284/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00388 285/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.03681 286/732, (1387, 13), 2025-07-04 00:00:00
Processed HK.01900 287/732, (2442, 13), 2025-07-04 00:00:00
Processed HK.06060 288/732, (1908, 13), 2025-07-04 00:00:00
Processed HK.03668 289/732, (1613, 13), 2025-07-04 00:00:00
Processed HK.02576 290/732, (181, 13), 2025-07-04 00:00:00
Processed HK.02562 291/732, (166, 13), 2025-07-04 00:00:00
Processed HK.01725 292/732, (1685, 13), 2025-07-04 00:00:00
Processed HK.03898 293/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02238 294/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02589 295/732, (41, 13), 2025-07-04 00:00:00
Processed HK.00163 296/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.03330 297/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00836 298/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.02600 299/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00017 300/732, (2460, 13), 2025-07-04 00:00:00
Processed HK.02172 301/732, (729, 13), 2025-07-04 00:00:00
Processed HK.09999 302/732, (1244, 13), 2025-07-04 00:00:00
Processed HK.00003 303/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00981 304/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.02628 305/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00956 306/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01137 307/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.01876 308/732, (1416, 13), 2025-07-04 00:00:00
Processed HK.01686 309/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.83690 310/732, (501, 13), 2025-07-04 00:00:00
Processed HK.01877 311/732, (1603, 13), 2025-07-04 00:00:00
Processed HK.02359 312/732, (1610, 13), 2025-07-04 00:00:00
Processed HK.01888 313/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.06881 314/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00200 315/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02629 316/732, (30, 13), 2025-07-04 00:00:00
Processed HK.01334 317/732, (242, 13), 2025-07-04 00:00:00
Processed HK.00002 318/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00016 319/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02601 320/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.00189 321/732, (2164, 13), 2025-07-04 00:00:00
Processed HK.00823 322/732, (2463, 13), 2025-07-04 00:00:00
Processed HK.02007 323/732, (2266, 13), 2025-07-04 00:00:00
Processed HK.02013 324/732, (1590, 13), 2025-07-04 00:00:00
Processed HK.00604 325/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.06088 326/732, (1962, 13), 2025-07-04 00:00:00
Processed HK.06936 327/732, (146, 13), 2025-07-04 00:00:00
Processed HK.02563 328/732, (105, 13), 2025-07-04 00:00:00
Processed HK.02577 329/732, (125, 13), 2025-07-04 00:00:00
Processed HK.02208 330/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02552 331/732, (1671, 13), 2025-07-04 00:00:00
Processed HK.00345 332/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.01729 333/732, (1814, 13), 2025-07-04 00:00:00
Processed HK.03880 334/732, (4, 13), 2025-07-04 00:00:00
Processed HK.00386 335/732, (2464, 13), 2025-07-04 00:00:00
Processed HK.02585 336/732, (144, 13), 2025-07-04 00:00:00
Processed HK.09639 337/732, (180, 13), 2025-07-04 00:00:00

In [59]:
print(df_ohcl['code'].drop_duplicates().shape)

quote_ctx.close()

(730,)

In [46]:
def super_trend_daily(row, df_ohcl, test=None):
	ticker_id = row['ticker_id']
	ticker_data = df_ohcl[df_ohcl['code'] == ticker_id].reset_index(drop=True)
	ticker_data = ticker_data.assign(
		supertd_change = 0,
		supertd_prev = 0,
		supertl=0,
		supertd=0,
		supert=0,
	)

	row['ticker_data'] = None
	if ticker_data is None or ticker_data.empty:
		print(f"Failed to fetch ticker_data for {ticker_id}")
		return row


	SUPERTd = ta.supertrend(high=ticker_data['high'], low=ticker_data['low'], close=ticker_data['close'],
			 length=10, multiplier=3.0, fillna=0.0)

	if SUPERTd is None or SUPERTd.empty:
		print(f"Failed to calculate Supertrend for {ticker_id} | 可能是上市时间太短。 {ticker_data.shape}")
		return row
	
	ticker_data['supert'] = SUPERTd['SUPERT_10_3.0']
	ticker_data['supertl'] = SUPERTd['SUPERTl_10_3.0']
	ticker_data['supertd'] = SUPERTd['SUPERTd_10_3.0']

	ticker_data['supertd_prev'] = ticker_data['supertd'].shift(1)

	ticker_data = ticker_data.assign(
		supertd_change = 0
	)
	condition = (ticker_data['supertd'] > 0) & (ticker_data['supertd_prev'] < 0)
	ticker_data.loc[condition, 'supertd_change'] = 1

	condition = (ticker_data['supertd'] < 0) & (ticker_data['supertd_prev'] > 0)
	ticker_data.loc[condition, 'supertd_change'] = -1

	row['ticker_data'] = ticker_data
	return row

In [47]:
def cal_technicals(row, ticker_data_df, test=None):
	ticker_data = row['ticker_data']
	if ticker_data is None:
		return row

	ticker_data = ticker_data.assign(
		EMA_13_daily=None,
		EMA_21_daily=None,
		EMA_144_daily=None,
		EMA_169_daily=None,
		SMA_5_daily=None,
		SMA_10_daily=None,
		SMA_20_daily=None,
		SMA_50_daily=None,
		SMA_100_daily=None,
		vegas=0,
	)
	row['ticker_data'] = None
	if ticker_data.empty:
		return row
	
	indicators = [
		(talib.EMA, "EMA_13_daily", 13),
		(talib.EMA, "EMA_21_daily", 20),
		(talib.EMA, "EMA_144_daily", 144),
		(talib.EMA, "EMA_169_daily", 169),
		(talib.SMA, "SMA_5_daily", 5),
		(talib.SMA, "SMA_10_daily", 10),
		(talib.SMA, "SMA_20_daily", 20),
		(talib.SMA, "SMA_50_daily", 50),
		(talib.SMA, "SMA_100_daily", 100),
	]

	for func, name, period in indicators:
		ticker_data[name] = func(ticker_data['close'], timeperiod=period)

	ticker_data = ticker_data.assign(SMA_5_Cross_SMA_20=0,)
	ticker_data['SMA_5_daily_prev'] = ticker_data['SMA_5_daily'].shift(1)
	ticker_data['SMA_20_daily_prev'] = ticker_data['SMA_20_daily'].shift(1)

	condition = (ticker_data['close'] > ticker_data['EMA_144_daily']) & (ticker_data['close'] > ticker_data['EMA_169_daily'])
	ticker_data.loc[condition, 'vegas'] = 1

	condition = (ticker_data['close'] < ticker_data['EMA_144_daily']) & (ticker_data['close'] < ticker_data['EMA_169_daily'])
	ticker_data.loc[condition, 'vegas'] = -1

	condition = (ticker_data['SMA_5_daily'] > ticker_data['SMA_20_daily']) & (ticker_data['SMA_5_daily_prev'] < ticker_data['SMA_20_daily_prev'])
	ticker_data.loc[condition, 'SMA_5_Cross_SMA_20'] = 1
	condition = (ticker_data['SMA_5_daily'] < ticker_data['SMA_20_daily']) & (ticker_data['SMA_5_daily_prev'] > ticker_data['SMA_20_daily_prev'])
	ticker_data.loc[condition, 'SMA_5_Cross_SMA_20'] = -1

	ticker_data = ticker_data.drop(columns=['SMA_5_daily_prev', 'SMA_20_daily_prev'])

	row['ticker_data'] = ticker_data
	return row

In [62]:
df = config_tickers.apply(super_trend_daily, axis=1, args=(df_ohcl, None))

print('cal super trend success.')

cal super trend success.

In [49]:
df = df.apply(cal_technicals, axis=1, args=(df_ohcl, None))
print('cal technicals success.')

cal technicals success.

In [50]:
ticker_result_df = pd.DataFrame()

for index, row in df.iterrows():
    if row['ticker_data'] is None or row['ticker_data'].empty:
        continue
    ticker_result_df = pd.concat([ticker_result_df, row['ticker_data']], axis=0)

In [51]:
ticker_result_df = ticker_result_df.dropna(subset=['EMA_169_daily'])
ticker_result_df = ticker_result_df.sort_values(by=['code', 'time_key']).reset_index(drop=True)

In [52]:
ticker_result_df = ticker_result_df[ticker_result_df['time_key'] >= last_date]  # 只保留最近的数据
ticker_result_df = ticker_result_df.sort_values(by=['code', 'time_key']).reset_index(drop=True)

In [53]:
technical_df = ticker_result_df[ticker_result_df['SMA_5_Cross_SMA_20'].rolling(10).sum() > 0]
technical_df = technical_df.reset_index(drop=True)
display(technical_df.sort_values(by='name').reset_index(drop=True))

,code,name,time_key,open,close,high,low,pe_ratio,turnover_rate,volume,...,EMA_21_daily,EMA_144_daily,EMA_169_daily,SMA_5_daily,SMA_10_daily,SMA_20_daily,SMA_50_daily,SMA_100_daily,vegas,SMA_5_Cross_SMA_20
0,HK.02505,EDA集团控股,2025-07-04 00:00:00,2.67,2.61,2.70,2.61,22.695,0.00032,141000.0,...,2.650221,2.830227,2.898866,2.620,2.615,2.64250,2.7145,2.76035,-1,0
1,HK.01070,TCL电子,2025-07-03 00:00:00,9.70,10.02,10.06,9.65,14.355,0.00312,7858171.0,...,9.632721,8.250502,7.969807,9.578,9.466,9.54500,9.8690,8.78030,1,1
2,HK.01070,TCL电子,2025-07-04 00:00:00,10.02,9.64,10.06,9.57,13.810,0.00313,7894081.0,...,9.633414,8.269667,7.989456,9.656,9.510,9.54450,9.8946,8.80960,1,0
3,HK.02522,一脉阳光,2025-07-04 00:00:00,13.96,13.76,14.06,13.52,0.000,0.02917,7533000.0,...,14.375244,24.502482,25.284784,13.664,13.556,13.92400,17.1680,25.10820,-1,0
4,HK.02522,一脉阳光,2025-07-03 00:00:00,13.60,13.90,14.36,13.48,0.000,0.05139,13272000.0,...,14.440006,24.652726,25.421984,13.580,13.470,14.07800,17.3288,25.30560,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,HK.08629,集信国控,2025-07-03 00:00:00,9.20,9.48,9.48,9.18,18.265,0.00172,17500.0,...,9.485184,9.595523,9.610985,9.178,9.345,9.60000,9.5402,9.57380,-1,0
229,HK.08629,集信国控,2025-07-04 00:00:00,9.20,9.30,9.32,9.13,17.919,0.00167,17000.0,...,9.467547,9.591447,9.607326,9.180,9.326,9.58650,9.5438,9.56360,-1,0
230,HK.01942,马可数字科技,2025-07-03 00:00:00,0.59,0.59,0.60,0.57,0.000,0.00620,7092000.0,...,0.547604,0.792934,1.010357,0.616,0.586,0.54325,0.4338,0.54990,-1,0
231,HK.01942,马可数字科技,2025-07-04 00:00:00,0.59,0.57,0.59,0.56,0.000,0.00635,7266000.0,...,0.549737,0.789859,1.005177,0.612,0.590,0.54925,0.4380,0.54590,-1,0
232,HK.03380,龙光集团,2025-07-04 00:00:00,0.89,0.90,0.92,0.88,0.000,0.00120,6797000.0,...,0.854102,0.898400,0.899081,0.882,0.852,0.84750,0.8496,0.90650,1,0

In [54]:
bull_df = ticker_result_df[(ticker_result_df['supertd'] > 0) & (ticker_result_df['supertd_change'] > 0) & (ticker_result_df['vegas'] > 0)]
bull_df = bull_df.sort_values(by=['code', 'time_key']).reset_index(drop=True)

In [55]:
supertd_vol_big = bull_df[bull_df['volume'] >= 15000000]  # 非常小体量的不考虑
supertd_vol_big = supertd_vol_big.reset_index(drop=True)
display(supertd_vol_big)

,code,name,time_key,open,close,high,low,pe_ratio,turnover_rate,volume,...,EMA_21_daily,EMA_144_daily,EMA_169_daily,SMA_5_daily,SMA_10_daily,SMA_20_daily,SMA_50_daily,SMA_100_daily,vegas,SMA_5_Cross_SMA_20
0,HK.00697,首程控股,2025-07-03 00:00:00,1.64,1.70,1.74,1.63,30.357,0.01845,134376600.0,...,1.608394,1.449615,1.427409,1.626,1.604,1.6095,1.6034,1.551007,1,0
1,HK.01108,凯盛新能,2025-07-04 00:00:00,4.95,5.11,5.27,4.83,0.000,0.14873,37182000.0,...,4.291457,3.936209,3.962584,4.606,4.448,4.2105,3.8990,3.809300,1,0
2,HK.02333,长城汽车,2025-07-04 00:00:00,12.80,13.08,13.40,12.70,8.169,0.01499,34760466.0,...,12.320613,12.549832,12.522327,12.544,12.284,12.2570,12.1376,12.702000,1,0

In [56]:
supertd_vol_mini = bull_df[(bull_df['volume'] < 15000000) & (bull_df['change_rate'] > 0.01)]
supertd_vol_mini = supertd_vol_mini.reset_index(drop=True)

# 小体量风险大，同时考虑交易量，确认稳定性
display(supertd_vol_mini)

,code,name,time_key,open,close,high,low,pe_ratio,turnover_rate,volume,...,EMA_21_daily,EMA_144_daily,EMA_169_daily,SMA_5_daily,SMA_10_daily,SMA_20_daily,SMA_50_daily,SMA_100_daily,vegas,SMA_5_Cross_SMA_20
0,HK.08606,倢冠控股,2025-07-03 00:00:00,0.138,0.128,0.138,0.138,0.0,0.00003,40000.0,...,0.103806,0.112107,0.110606,0.104,0.0995,0.1031,0.11172,0.12879,1,1

In [57]:
bear_df = ticker_result_df[(ticker_result_df['supertd'] < 0) & (ticker_result_df['supertd_change'] < 0) & (ticker_result_df['vegas'] < 0)]
bear_df = bear_df.sort_values(by=['code', 'time_key']).reset_index(drop=True)
# display(bear_df)

In [58]:
supertd_tech_df = ticker_result_df[
	(ticker_result_df['supertd'] > 0) & (ticker_result_df['supertd_change'] > 0) & (ticker_result_df['vegas'] > 0)
	& (ticker_result_df['SMA_5_Cross_SMA_20'].rolling(window=10).sum() > 0)]

supertd_tech_df = supertd_tech_df.sort_values(by=['code', 'time_key']).reset_index(drop=True)
# 符合supertd条件，且近期SMA有上穿
supertd_tech_df[supertd_tech_df['time_key'] >= last_date].sort_values(by='name').reset_index(drop=True)
bull_tech_vol_df = supertd_tech_df[supertd_tech_df['volume'] >= 15000000]  # 非常小体量的不考虑

display(bull_tech_vol_df)

Empty DataFrame
Columns: [code, name, time_key, open, close, high, low, pe_ratio, turnover_rate, volume, turnover, change_rate, last_close, supertd_change, supertd_prev, supertl, supertd, supert, EMA_13_daily, EMA_21_daily, EMA_144_daily, EMA_169_daily, SMA_5_daily, SMA_10_daily, SMA_20_daily, SMA_50_daily, SMA_100_daily, vegas, SMA_5_Cross_SMA_20]
Index: []

[0 rows x 29 columns]